### ISSUE TITLE
Improve KVS API

### ISSUE THREAD

**Issue by doru91** [project-chip/connectedhomeip#10283]
#### Problem
KVS API uses char* as keys. Vendors which don't support NVM saving using strings as keys need to translate from a char* key to a number key and viceversa.

 #### Proposed Solution
Use numbers as keys for the KVS. A higher layer Matter should do the translation between char* to numbers if needed. These changes could be easily integrated in the *Config.{cpp/h} files which are receiving numbers as keys. 

See also https://github.com/project-chip/connectedhomeip/pull/9489

cc @tcarmelveilleux @msandstedt

**Comment by tcarmelveilleux** [comment]
It seems more and more like there will need to continue being "core SDK" usage of direct storage in the foreseeable future. To make the examples and implementation simpler, I make the following recommendation:

- Define an SDK wide hierarchical allocation scheme for keys where:
  - Keys are `uint32_t`
  - There is some structure, for example FabricInfo for Fabric Index 0xCD is key `(0x10_00_0000 | FabricIndex << 16)` == `0x10_CD_0000`. That is just an example, but shows how we can scope different types of data by some important sub-index to shard storage
  - The allocation by SDK modules of this entire encoding is documented in a single file, to keep track of who uses what and why
  - The allocation scheme reserves a large amount of space for non-SDK usage
- Add new `Sync[Get|Set|Delete]KeyValue` with a `uint32_t` key instead of string
- Temporarily steer the above to use the hex of the key ID as the string until all code is converted to use uint32_t key calls everywhere.
- Move all SDK usage of `Sync[Get|Set|Delete]KeyValue` to use `uint32_t` key
- Add a `SyncIterateKeys()` iterator to the interface, to be able to list all keys stored.

The advantages of this scheme would be as follows:
- Avoid arbitrary length string storage/processing (biggest problem today)
- Clearly be able to determine which modules use what storage and why
- Simplify mapping between API and storage APIs where keys are scalars (which is very common)
- It would be compatible with string-based or database-driven key storage, since the constraints of a small width scalar allow making simplifications/optimizations

**Comment by ah-u** [comment]
Copying slack conversation here:

> If you look at a few simple examples: storing an attribute value (endpoint id, cluster ID, attribute ID), storing a group or scene table, or generally speaking, storing an associative container with arbitrary keys and a variable number of entries, it would be difficult to map these use-cases to a statically assigned 32-bit key namespace without punting much of the ID management to the product. Some part of the key you might not have control over (MAC IDs, group IDs). We have designed two major revisions of our persistent storage and both support what we call hierarchical keys: v1 used a fixed key length of 6 bytes for the key, in v2 we support variable length keys (1..32 bytes). Both were specifically designed to support a modular and extensible cluster and application endpoint framework that does all of the heavy lifting. With these hierarchical keys you can do queries like "find all attributes of cluster X on endpoint Y", or "delete all bindings for endpoint X, cluster Y". It  does not require a central place for managing all key IDs potentially used in a product. If you add or remove endpoints, clusters, or attributes with an OTA update, or if you build a bridge product, which dynamically adds and removes endpoints, clusters and attributes based on what devices and features it finds on the other side of the bridge, this makes life a lot easier for product manufacturers. Admittedly, it makes life harder for platform vendors. We do both, so investing effort once at the platform level rather than many times for each product made sense.
