### ISSUE TITLE
A command with no data struct will cause use of an un-initialized TLV reader

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#10501]
#### Problem
`CommandHandler::ProcessCommandDataElement` does this:
```
    chip::TLV::TLVReader commandDataReader;
...

    err = aCommandElement.GetData(&commandDataReader);
    if (CHIP_END_OF_TLV == err)
    {
        err = CHIP_NO_ERROR;
        ChipLogDetail(DataManagement, "Received command without data for cluster " ChipLogFormatMEI, ChipLogValueMEI(clusterId));
    }
```
But now commandDataReader is not initialized, and we proceed to pass it to `DispatchSingleClusterCommand` which will try to read from it.

 #### Proposed Solution
1. Write a test that exercises this case.  In particular, this should send no data for a command that normally _does_ have fields that get sent.
2. Fix the code to handle this correctly.

@yunhanw-google @mrjerryjohns

**Comment by mrjerryjohns** [comment]
Our current `CommandSender` implementation _always_ inserts the data payload struct (even if it is empty) right? So, that condition should never get triggered on the handler?

What should be the spec defined behavior here? Is not sending the data element permitted? Looking at the spec, it's quite mum on this...

**Comment by mrjerryjohns** [comment]
I'd be fine with just initializing the TLVReader with a null buffer. That ensures that subsequent decode will fail. This also reduces the API churn.

**Comment by bzbarsky-apple** [comment]
> So, that condition should never get triggered on the handler?

You're as assuming that the sender is using our code.  And not being malicious.   We should not be assuming that.

**Comment by bzbarsky-apple** [comment]
We can't defer this: this is a known bug where we read un-initialized memory and then act on it, which is really bad from a security perspective.

**Comment by erjiaqing** [comment]
I think this issue is already fixed in previous refactors

1. In `CommandHandler::ProcessInvokeRequest`

https://github.com/project-chip/connectedhomeip/blob/0861153771b0d6b2a10910767e17bb98b6727b63/src/app/CommandHandler.cpp#L97-L103

(Which ensures `invokeRequests` is a valid parser with a reader holding lists.

2. Then we have

https://github.com/project-chip/connectedhomeip/blob/0861153771b0d6b2a10910767e17bb98b6727b63/src/app/CommandHandler.cpp#L128-L136

(Which ensures it is holding exactly one list (as we only supports one request today))

3. And we have

https://github.com/project-chip/connectedhomeip/blob/0861153771b0d6b2a10910767e17bb98b6727b63/src/app/CommandHandler.cpp#L305-L326

This should ensure the payload passed to DispatchCommand is a valid reader.

For group writes, we also have

https://github.com/project-chip/connectedhomeip/blob/0861153771b0d6b2a10910767e17bb98b6727b63/src/app/CommandHandler.cpp#L362-L370

**Comment by bzbarsky-apple** [comment]
Attaching a change to the commands test that shows the problem.  The decoding of the command either fails if there is no fields struct (which the spec allows), if the random "control byte" value is not of type struct, or we hit ASAN errors trying to decode if the control byte happens to be "struct". 

Which actually points out a second problem: validly not including a field struct at all for a command that has no fields will fail decode!  This is an absolute must-fix for spec compliance.
[demonstrate-uninitialized-reader.txt](https://github.com/project-chip/connectedhomeip/files/9003479/demonstrate-uninitialized-reader.txt)
