### ISSUE TITLE
Add events to application clusters XML files

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#11023]
#### Problem
Add events to application clusters XML files
Basic Cluster
Diagnostics
Button

**Comment by trombadore** [comment]
This is blocking Matter Test Harness.

For certain controller certification tests, a simulated node needs to be able to handle events like StartUp, ShutDown and Leave. @vivien-apple's simulated nodes for these controller tests leverage the matter stack to handle events. Therefore this bug needs to close so that the Matter stack supports events and thus the simulated nodes leveraged by the test harness can handle events as well.
