### ISSUE TITLE
[TC-TSUIC-2.2] Test steps 2C, 3G and 4C Validation Failing.

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#11052]
#### Problem
Validation for the following test steps are failing 
- TH writes a value of greater than 1 TemperatureDisplayMode attribute of DUT
- TH writes a value of greater than 5 to KeypadLockout attribute of DUT
- TH writes a value of greater than 1 to ScheduleProgrammingVisibility attribute of DUT
In all these test steps, the DUT should return an error CONSTRAINT_ERROR (0x87), however the cluster apps are successfully writing values greater than specified into the respective attributes.

**Attached logs from YAML test script for reference.**
[TC_TSUIC_2_2_Failures.txt](https://github.com/project-chip/connectedhomeip/files/7427084/TC_TSUIC_2_2_Failures.txt)

**Comment by yufengwangca** [comment]
It looks we are missing the constraint for those attributes

**Comment by yufengwangca** [comment]
These attributes seems silab proprietary and I couldn't find them in spec. The SDK definition for those values are in 
src/app/zap-templates/zcl/data-model/silabs/types.xml

@kvikrambhat 
What is the range definition for those attribute? We should add the conformance check in
src/app/clusters/thermostat-user-interface-configuration-server/thermostat-user-interface-configuration-server.cpp

**Comment by yufengwangca** [comment]
@eve-cxrp 

I though this issue should be addressed by https://github.com/project-chip/connectedhomeip/pull/11058, could you confirm?

**Comment by eve-cxrp** [comment]
@yufengwangca Yes this is fixed by the issue. As you can see [here](https://github.com/project-chip/connectedhomeip/blob/master/src/app/clusters/thermostat-user-interface-configuration-server/thermostat-user-interface-configuration-server.cpp#L25) the function is added to the endpoint_config.h and is called then. 

We have encountered a similar problem which is caused by a compiler bug. There was also a slack discussion related to this. 

The discussion started [here](https://csamembers.slack.com/archives/G014G30SVV0/p1643648826242669) and the relevant findings are [here](https://csamembers.slack.com/archives/G014G30SVV0/p1643650820974929)

**Comment by yufengwangca** [comment]
@eve-cxrp 

Where is the xml definition for ThermostatUserInterfaceConfiguration cluster? I only see the server callback in our SDK

**Comment by eve-cxrp** [comment]
> @eve-cxrp
> 
> Where is the xml definition for ThermostatUserInterfaceConfiguration cluster? I only see the server callback in our SDK

[Here](https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/silabs/ha.xml#L79)

**Comment by bzbarsky-apple** [comment]
Fixed in #12325

**Comment by bzbarsky-apple** [comment]
@kvikrambhat That said, I do not see any (even disabled) YAML tests trying to exercise this...
