### ISSUE TITLE
Need to sort out error-handling in on-off cluster code

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#1108]
#### Problem
Consider what happens when an invalid endpoint id is used in an on-off cluster command like "on".

Right now we land in `chipZclClusterOnOffServerCommandOnRequestHandler` which calls `setOnOffHandler` which:

1. Calls `setOnOff`
2. Calls `chipZclSendDefaultResponse` with a success status.

`setOnOff` calls `chipZclWriteAttribute` which will fail (and return a failure status!) if the endpoint id is not valid.  But all of `setOnOff`, `setOnOffHandler`, `chipZclClusterOnOffServerCommandOnRequestHandler` return void, so an error return from `chipZclWriteAttribute` is just silently ignored and never affects any behavior.

The caller of `chipZclClusterOnOffServerCommandOnRequestHandler` is `chipZclOnOffClusterServerCommandParse`, which _does_ return a status.  But it obviosly can't get a status from `chipZclClusterOnOffServerCommandOnRequestHandler`.

So if a command is sent for an invalid endpoint, there is no indication anywhere that anything is wrong, apart from the command having no effect.  That seems a bit unexpected.

 #### Proposed Solution
We should probably either pass the right status to `chipZclSendDefaultResponse` or return it back to `chipZclOnOffClusterServerCommandParse` or both.  I'm not sure whether it should be both or not; the semantics of this return value at different levels aren't really very clear to me.

@tecimovic @bhaskar-apple

**Comment by vivien-apple** [comment]
@bzbarsky-apple Sorry if that's a stupid question. I'm trying to understand what this issue is about exactly.

Assuming one is using chip-tool to set the endpoint, the current code should returns EMBER_ZCL_STATUS_UNSUPPORTED_CLUSTER if the cluster is not supported on the endpoint because of https://github.com/project-chip/connectedhomeip/blob/fbbf127d835f08d5304de446da38c16d79014ee7/examples/wifi-echo/server/esp32/main/gen/call-command-handler.c#L86

If one uses and endpoint that does not exists, there is no indication that something went wrong (which I agree is strange) because we will hit https://github.com/project-chip/connectedhomeip/blob/6b687e6df2a308312989ea56f9dcd083eebd2801/src/app/util/util.cpp#L419

But I do not see how you will end up in the on-off cluster server code with an invalid endpoint. I wonder what I'm missing here.

**Comment by bzbarsky-apple** [comment]
This issue was about the "dotdot" code that we have long since removed from the tree.  Not relevant anymore.
