### ISSUE TITLE
[TC-TSTAT-2.2] Command SetpointRaiseLower Failing

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#11714]
Summary :
As per test plane the command SetpointRaiseLower is to be send from the TH and should return a successful status, however when we try to use this command in the YAML test scripts it seem to always fail, please refer attached screenshots and logs

Spec Screenshot:
![image](https://user-images.githubusercontent.com/84442963/141412751-20a3c38c-be57-4b97-a9cb-bbfd9375a98e.png)

Test-plan Screenshot:
![image](https://user-images.githubusercontent.com/84442963/141412654-f14a85d9-9ac0-44f2-9782-c6cc19e717c1.png)

Test execution log file:
[TSTAT_2_2.txt](https://github.com/project-chip/connectedhomeip/files/7525029/TSTAT_2_2.txt)

**Comment by chrisbeach59** [comment]
I believe that this is related to the auto feature being enabled by the #define in thermostat-server.cpp, due to the issue with Feature Map on little endian machines.  

Can you please send me the full transcript of the run.  There are missing steps in the excel file.  I think this is causing a violation of the constraints imposed by.  The full transcript will help me to resolve if this is not the designed behavior.
