### ISSUE TITLE
[ble connect]controller commissioning dut fail by ble

### ISSUE THREAD

**Issue by Suguotao** [project-chip/connectedhomeip#12258]
dut:k32w06
controller:raspbeerypi 4B+ 
#### Problem
 * expected behavior
    commission successfully
 * actual behavior
     commission faily
 * steps to reproduce
   a. cd  /home/ubuntu/connectedhomeip
   b. source ./out/python_env/bin/activate
   c. chip-device-ctrl
   d. connect -ble 3840 20202021 12344321

   then ,i found dut will crash，can't work
 * screenshots, images, logs, etc.
 >
[controller_log.txt](https://github.com/project-chip/connectedhomeip/files/7601779/controller_log.txt)
[dut_log.txt](https://github.com/project-chip/connectedhomeip/files/7601780/dut_log.txt)

**Comment by fuxiaoming-lumi** [comment]
Let me add more details.

**Comment by fuxiaoming-lumi** [comment]
DUT: k32w06 DK (Branch TE7 patch this commit )
:raspbeerypi 4B+

Problem
expected behavior
commission successfully

actual behavior
commission faily

steps to reproduce
a. cd /home/ubuntu/connectedhomeip
b. source ./out/python_env/bin/activate
c. chip-device-ctrl
d. connect -ble 3840 20202021 12344321

then ,i found dut will crash，can't work

screenshots, images, logs, etc.

controller_log.txt
dut_log.txt

**Comment by cecille** [comment]
Is this still happening on master?

**Comment by woody-apple** [comment]
Please re-verify and re-open if this is still happening!

**Comment by fuxiaoming-lumi** [comment]
After many tests, it is confirmed that it is caused by a hardware problem. We can close this ticket.
