### ISSUE TITLE
Media Cluster issues

### ISSUE THREAD

**Issue by chrisdecenzo** [project-chip/connectedhomeip#13606]
#### Problem
1. ApplicationLauncher ApplicationEP type has endpoint as a string rather than a uint16
2. ApplicationLauncher read of currentApp attribute does not allow for null
3. chip-tool does not allow read of currentApp attribute

**Comment by lazarkov** [comment]
1. ApplicationLauncher ApplicationEP type has endpoint as a string rather than a uint16. Duplicate, noted [here](https://github.com/project-chip/connectedhomeip/issues/13214)
2. ApplicationLauncher read of currentApp attribute does not allow for null
3. ~~chip-tool does not allow read of currentApp attribute~~ Resolved
