### ISSUE TITLE
Long pairing code is not available both in Raspberrypi and M5 stack  platform

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#13661]
#### Problem

In the app-clusters-app log, Its not printing the long manual pairing QR code. (21 digit code)

We observe that, logs has, General QR Code and the manual 11 digit short code.
[manual_code.txt](https://github.com/project-chip/connectedhomeip/files/7891258/manual_code.txt)

**Comment by dhrishi** [comment]
@sowmyassp Previously, ESP32 example had the logic to calculate and print the onboarding payload in the example itself and hence we printed both long and short manual pairing codes. Recently, the [implementation was updated](https://github.com/project-chip/connectedhomeip/pull/11668/commits/b67cdaf461dfbaf6ccd6cfc34407d20421fc6c8f) to use the [CHIP common code API PrintOnboardingCodes](https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/OnboardingCodesUtil.cpp#L37) instead. This API calls  [GetManualPairingCode](https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/OnboardingCodesUtil.cpp#L199) that has the ability to calculate only the short manual code and not the long one.

So, this needs to be fixed in the CHIP SDK
