### ISSUE TITLE
11618, we are not handling properly external attributes

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13935]
in this case... We need to do something. We don&#x27;t really know if it will succeed.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/util/attribute-table.cpp#L432-L437

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `bug` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by andy31415** [comment]
The check seems to be on the else branch after:

```
380     // write the data unless this is only a test
381     if (!justTest)
382     {
```

justTest is set to true by emberAfVerifyAttributeWrite which I do not see used anywhere in the code. Is this correct? can we just drop this 'just test' branch?

I.e. this TODO seems easy enough, but I am unsure if it is actually a V1 blocker. Keeping as blocker because easy to change.
