### ISSUE TITLE
Here, most interfaces are just calling ConnectivityManager interfaces, this is because the ConnectivityProvides some

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14172]
bootstrap code for the wpa_supplicant. However, we can wrap the wpa_supplicant dbus api directly (and remove the related code in ConnectivityManagerImpl).

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/Linux/NetworkCommissioningWiFiDriver.cpp#L35-L40

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by turon** [comment]
Not super clear if this issue is for *all* Linux configurations, or only Linux platform builds that desire to maintain exclusive control over WPA supplicant management (and not use the Matter SDK provided integration).

I believe it is the later, in which case, this issue should not be blocking for the v1 release.

Removing tag `v1_triage_split_4`
