### ISSUE TITLE
"Removed Fabric Index 2 with Error "Undefined error:50"" seen when tried to Remove all Fabrics from chip-tool with 2 fabrics

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#15942]
#### Problem
"Removed Fabric Index 2 with Error "Undefined error:50"" seen when tried to Remove all Fabrics from chip-tool with 2 fabrics

SHA: c0373bbc244894909fb0acf55c73444e14088208

Steps to reproduce:

1. Pair M5 board with chip tool 1  and toggle on/off works fine. 
2. Enable pairing from chip tool 1 and pair M5 board with Chip tool 2.
3. Toggle on / off light on M5 works fine
4. Navigate to Fabric Management on chip tool 1 and perform "Remove All Fabrics"
5. See attached screenshot, error is seen when trying to remove fabric index 2 and chip tool 2 is still able to toggle on/ off light on M5. Chip tool 1 is not able to toggle light as expected. 
 
Note: Chip tool 1 and chip tool 2 are both on different iOS devices but on the same network. 

![Remove-all-Fabrics-Failure](https://user-images.githubusercontent.com/99367303/157153551-5b968fe8-563a-47c9-898a-e3fd568d9102.jpeg)
[chiptool1-logs-remove-all-fabrics.txt](https://github.com/project-chip/connectedhomeip/files/8202207/chiptool1-logs-remove-all-fabrics.txt)
[chiptool2-logs-remove-all-fabrics.txt](https://github.com/project-chip/connectedhomeip/files/8202208/chiptool2-logs-remove-all-fabrics.txt)
[M5-logs-remove-all-fabrics.txt](https://github.com/project-chip/connectedhomeip/files/8202211/M5-logs-remove-all-fabrics.txt)

**Comment by bzbarsky-apple** [comment]
> Undefined error:50

That would be `CHIP_ERROR_TIMEOUT`.  Created https://github.com/project-chip/connectedhomeip/pull/15980 to make this nicer.

Past that, this is a bug in the CHIPTool client.  There are two fabrics, 1 and 2.  It's on fabric 1.  It removes fabric 1, then tries to remove fabric 2.  Since fabric 1 has been removed, its attempt to remove fabric 2 fails (can't even get a response, because the encryption keys for fabric 1 are gone) and it times out.

A "remove all fabrics" operation would need to remove all the fabrics _except_ the current one, then remove the current one.

@sagar-apple @kean-apple
