### ISSUE TITLE
[TC-MC-9.2] Simulated test crashing when made a run

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16129]
Summary:
               when trying out simulated device test case for "[TC-MC-9.2]" we are observing a crash showing response as : "Response Failure: IM Error 0x000005C3: General error: 0xc3"

Execution logs :
[TC_MC_9_2_app_side.txt](https://github.com/project-chip/connectedhomeip/files/8233998/TC_MC_9_2_app_side.txt)
[TC_MC_9_2_CHip_tool.txt](https://github.com/project-chip/connectedhomeip/files/8233999/TC_MC_9_2_CHip_tool.txt)

**Comment by krypton36** [comment]
This issue appears to be happening, because `MatterPostAttributeReadCallback` gets called before sending report in `BuildAndSendSingleReportData` which causes the thread to End Early and terminate the message transmission to the controller. The simulated app will need to wait until after the SenReport is complete and then move on to the next test. This will require SDK changes, assigning to @vivien-apple to implement changes.

Steps to reproduce:
1. Generate Attached simplified YAML for simulated app
2. Compile simulated app
3. Start simulated app
4. Pair simulated app with chip-tool
5. Run the following chip-tool command: `chip-tool applicationbasic read application-version 1 1 `


[Test_TC_MC_9_2_Simulated.txt](https://github.com/project-chip/connectedhomeip/files/8235212/Test_TC_MC_9_2_Simulated.txt)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.

**Comment by manjunath-grl** [comment]
This issue needs to be closed.
