### ISSUE TITLE
Door Lock cluster attributes missing

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#16606]
Summary:
               As per test-plan need to read and write attribute "UserCodeTemporaryDisableTime" "NumberOfHolidaySchedulesSupported" and "RequirePINforRemoteOperation"
showing attribute missing when we executed.

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/159878354-e82c30e3-eff6-406d-b139-d5a8fd72e5f3.png)
![image](https://user-images.githubusercontent.com/84442963/159878482-f87184dd-1846-4487-bd94-17c2c3bfa253.png)

Execution screenshot and logs:
![RewPINRP](https://user-images.githubusercontent.com/84442963/159879357-01b4cdfe-002d-49de-9fc0-788fd9d0116a.png)
[RequirePINforRemoteOperation.txt](https://github.com/project-chip/connectedhomeip/files/8339839/RequirePINforRemoteOperation.txt)

**Comment by mlepage-google** [comment]
Some of those attributes are optional, so may not be present.

Nonetheless, I would request that for ease of testing access control and privileges, that we at least provide enough optional attributes (and commands and events) so that we have one for each of the privilege levels (view, operate, manage, administer).

**I.e., we should ensure our door lock examples have some attributes and commands that require manage or administer privilege.**
