### ISSUE TITLE
[TE8] Add support for dynamic endpoints to Test harness GUI

### ISSUE THREAD

**Issue by toktocke** [project-chip/connectedhomeip#16985]
#### Problem
In order to certify a Matter Bridge, the test harness needs to support the possibility to configure the endpoint ID for the cluster to test.

 #### Proposed Solution
Add support for configurable endpoint ID to the test harness GUI.
Similar to what is possible from `chip-tool`. E.g:
`./out/chip-tool tests Test_TC_CC_2_1 --endpoint 1`

**Comment by svigelj** [comment]
This is still a problem with the latest test harness. All tests for device clusters (eg. OnOff) are run on **endpoint 1** (on endpoint 1 in all bridge examples there is an Aggregator device type, not an actual device).

In order to proceed with running tests for multiple device types, we need to be able to specify on which endpoint a test should be run. This is a hard blocker for us. Has there been any progress regarding that?
