### ISSUE TITLE
[TC-IDM-2.2]While verifying Read Request Message to the DUT from TH to read any attribute to an unsupported node throws an invalid error instead UNSUPPORTED_NODE(0x9B)

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17500]
#### Problem
As per Test-Plan test step 13  While verifying Read Request Message to the DUT from TH to read any attribute to an unsupported node throws an Run command failure instead UNSUPPORTED_NODE(0x9B).

 * Expected behavior:-UNSUPPORTED_NODE(0x9B)
 * Actual behavior:- Run command failure: ../../third_party/connectedhomeip/src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:174: CHIP Error 0x00000032: Timeout

 * steps to reproduce:- 
While pairing provided nodeID as 1 
./chip-tool pairing ble-wifi 1 zigbee1 matter123 20202021 3840
To verify test step 13 of this test-case[TC-IDM-2.2] provided nodeID as 2
./chip-tool basic read product-name 2 0

 * system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/2982c0ca0623773327def4cc7180d07f6b959c42
Dut: All-Clusters-app

Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-2-2-report-data-action-from-dut-to-th

Spec Reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#ref_IM.StatusCodeTable

PFA log below:-
[Unsupported NodeID.txt](https://github.com/project-chip/connectedhomeip/files/8512792/Unsupported.NodeID.txt)

**Comment by yunhanw-google** [comment]
Per jerry, https://github.com/project-chip/connectedhomeip/issues/16705#issuecomment-1104440723, so we need to close it.

**Comment by yunhanw-google** [comment]
@bzbarsky-apple  since we are not supporting unsupported_node, I think timeout error is valid here?

**Comment by bzbarsky-apple** [comment]
The test plan described above can't be tested with the 1.0 SDK at all.  

The test steps above, in particular, would _not_ lead to UNSUPPORTED_NODE even if that were implemented.  They would just lead to a discovery error, or no error at all, just talking to the wrong node.

A test step that _could_ lead to UNSUPPORTED_NODE would involve sending an actual Node id in a path that does not match the right Node id.  And as I said, the current SDK cannot do it.  And yes, the only place where this would be useful is proxies, and proxies are out of scope for 1.0, so it's not getting implemented for 1.0.

So that's the summary:

1. The test plan cannot be tested with the SDK.
2. The steps above do not test what the test plan wants to test.

**Comment by Rajashreekalmane** [comment]
@bzbarsky-apple Thank you.
