### ISSUE TITLE
Use-after-free when expiring secure sessions

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#17558]
#### Problem
The current setup we have for sessions is as follows:

1. `Session` has virtual `Retain`/`Release` methods.
2. These are no-ops for group and secure sessions.
3. `UnauthenticatedSession` uses the refcounting to manage its lifetime.
4. `SessionHandle` refcounts the session it's pointing to in its constructor/destructor.
5. `SessionHolder` refcounts the session it's pointing to and will clear its pointer to the session when the session is being destroyed.

The issue arises with secure sessions, which are not reference counted.  Instead we manually expire them in various cases; see the output of `git grep "Expire" | grep Pairing`.  When these are expired, any live `SessionHandle` objects end up with dangling pointers, and their destructor will perform a use-after-free virtual call to `Release`.

Right now this is covered up by the fact that secure sessions are allocated out of a fixed-size `BitmapObjectPool` (in `SecureSessionTable`), so a release back into the pool does not actually deallocate the memory.  It also seems to not poison the vtable pointers, so the virtual calls succeed.

Changing that pool to an `ObjectPool` immediately blows up our unit tests.

In particular, `SessionManager::ExpirePairing(const SessionHandle & session)` is broken-by-design right now, since it guarantees that we will have a use-after-free when the caller's `SessionHandle` is destroyed.

 #### Proposed Solution
Not entirely clear.  One option is to make secure sessions actually be refcounted, with the `SessionManager` holding one of the refs, and `Expire*` clearing that ref, but the actual release back into the pool being deferred until the refcount goes to zero...  I think @kghost was going to give this a shot and see how it goes.

@kghost and I also considered doing the actual `Expire*` releases async so that they happen when we have an empty stack and hence no `SessionHandle`s hanging around, but that seems like it would introduce a bunch of possible racy behavior and complexity...

Any other bright ideas?

@msandstedt @kghost @mrjerryjohns @Damian-Nordic @yufengwangca

**Comment by mrjerryjohns** [comment]
> but the actual release back into the pool being deferred

This is not viable, since we need to be able to forcibly evict a session and replace it with a new one as part of the LRU-scheme being implemented in #17298, specifically, Tenet #2.

I think we need to pivot away from viewing sessions as 'ref-counted', since that gives the impression that its lifetime is in some ways controlled and effected by the total number of active users of that session, and that when the user count goes to 0, it somehow kills that session. We know this to not be true in terms of use-cases - we want sessions to linger so that they're available for us when clients express future interest in using those to interact with peers.

I think we should pivot away from using `SessionHandle` and to solely using `SessionHolders`. This provides a mechanism where you can have multiple clients of a session 'tack on' on to the list of holders of a session, and when that session expires, they all get notified. This avoids the problem with SessionHandles not having a means to actually 'null out' their internals when a session is forcibly evicted/removed by SessionManager.

**Comment by bzbarsky-apple** [comment]
> since we need to be able to forcibly evict a session and replace it with a new one as part of the LRU-scheme being implemented in https://github.com/project-chip/connectedhomeip/issues/17298

That might still work, no?  It would only fail if the session we choose to evict has the property that after it's dropped from all the session holders (which we would notify about the session going away) it _still_ has outstanding references.  Which means there is a SessionHandle around somewhere pointing to it.  Since SessionHandle is only supposed to be used for stack temporaries, this would only happen if this least-recently-used session is actively being referenced by something on the callstack right now, which seems pretty unlikely....

> I think we should pivot away from using SessionHandle and to solely using SessionHolders.

The concern is what happens with "on the stack" session references.  How are sessions to be represented in stack temporaries, including function arguments, without ending up with dangling pointers if callees happen to expire a session?

**Comment by kghost** [comment]
The idea executes pretty well in PR #17599

The session object is allocated when new pairing request arrives, it is very rare (if not impossible) that some stack variable is holding a `SessionHandle` to our chosen session to evict.

Although we can not guarantee that the evicted session is released immediate, but by LRU, it is VERY likely being released immediately. additionally if first try fails, we can try another one, evict the second least used session. greatly increase the chance we can get a free slot for the new session.
