### ISSUE TITLE
 [TC-TSTAT-1.1] DUT fails to list the supported commands for GeneratedCommandList attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17688]
#### Problem
As per the Test-Plan, GeneratedCommandList attribute should list the supported commands that is GetWeeklyScheduleResponse and 
GetRelayStatusLogResponse but currently DUT responds with 0 entries.

 * expected behavior:- DUT should responds with supported commands. 
 * actual behavior:- 0 entries

 * steps to reproduce:-./chip-tool thermostat read generated-command-list 1 1

 *system configuration:-
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 077e44eadf46f349916b3f4f358da6126be2ed48
Dut: Thermostat app 
 
PFA log below:-
[GeneratedCommandList.txt](https://github.com/project-chip/connectedhomeip/files/8554422/GeneratedCommandList.txt)

Test-plan reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/thermostat.adoc#tc-tstat-1-1-global-attributes-with-server-as-dut

**Comment by bauerschwan** [comment]
@Rajashreekalmane please close if you agree.

**Comment by bauerschwan** [comment]
Indeed the all-cluster-app supports SCH so GetWeeklySchedule is contained in AcceptedCommandList attribute. Therefore GetWeeklyScheduleResponse has to be contained in GeneratedCommandList attribute.

But the optional command GetRelayStatusLog is not contained in AcceptedCommandList attribute.
Therefore GetRelayStatusLogResponse shall not be contained in GeneratedCommandList attribute.

**Comment by bauerschwan** [comment]
@chrisbeach59 who is responsible for this?

**Comment by Rajashreekalmane** [comment]
Yes DUT (Thermostat app) support  GetWeeklySchedule which is  mandatory so it  should print the ID of it while running the "./chip-tool thermostat read generated-command-list 1 1"

**Comment by bauerschwan** [comment]
For me this looks like a zap issue because the GENERATED_COMMANDS in the zap-generated file endpoint_config.h contains wrong information. At least this is the case with code based on TE9 tag.

Here as an example the ZAP UI of our DUT:
<img width="792" alt="Screenshot 2022-05-17 at 09 47 25" src="https://user-images.githubusercontent.com/62264998/168758336-66615984-5320-4e71-9663-91fe22034eab.png">

Here the GENERATED_CLUSTERS in endpoint_config.h:
<img width="634" alt="Screenshot 2022-05-17 at 09 48 02" src="https://user-images.githubusercontent.com/62264998/168758540-81036906-02b9-4422-aa13-dd97f2d094c7.png">

Here the GENERATED_COMMANDS in endpoint_config.h:
<img width="385" alt="Screenshot 2022-05-17 at 09 48 41" src="https://user-images.githubusercontent.com/62264998/168758725-91683163-090e-428e-9ce1-862748330aaa.png">

So this is definitively wrong and should be fixed on zap side.

**Comment by bzbarsky-apple** [comment]
Did this not get fixed in https://github.com/project-chip/connectedhomeip/pull/17833 ?

**Comment by bzbarsky-apple** [comment]
The answer is: No, it did not.  For thermostat, we are very definitely listing response commands which are not enabled, and correspond to request commands that are also not enabled, in the "AcceptedCommandList", which is all sorts of broken.

**Comment by bzbarsky-apple** [comment]
@erjiaqing

**Comment by chrisbeach59** [comment]
@Rajashreekalmane only setpointraiselower is mandatory.   It is mandatory if schedule is enabled.  Scheduling is not supported in R1

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/zap/pull/515 will fix things.
