### ISSUE TITLE
ClusterBase does not notify application when subscription has terminated

### ISSUE THREAD

**Issue by s-mcclain** [project-chip/connectedhomeip#17962]
#### Problem
 ClusterBase supports OnSuccess/OnFailure occurences for attribute subscriptions, however, as subscriptions are persistent for longer than a single transaction. So unlike how applications can free allocated contexts on the first attribute response callback, applications need to be able to know when a subscription has been terminated to be able to free up an allocated context.

There is an 'OnDone' callback, however, the ClusterBase does not allow for registering for this callback exception for when writing to an attribute. Although there may be an expectation that we'd see a call for ReadResponseFailureCallback when a subscription has been terminated due to a failure, I have not seen this getting called. This is also not a very reliable or clear way to know if the subscription has been terminated yet.

A second problem is that, ClusterBase SubscribeAttribute() function does not allow for being able to pass in a 'keepPreviousSubscriptions' so that devices may be able to support multiple subscriptions.

 #### Proposed Solution
In ClusterBase, add support for OnDone callback to allow for applications to register for this callback whenever the subscription has completed.

For the second problem, add support for passing in 'keepPreviousSubscriptions' argument inside SubscribeAttribute and SubscribeEvent.

**Comment by mrjerryjohns** [comment]
The ReadResponseFailureCallback isn't called because the ClusterBase APIs all enable re-subscriptions by default. Which means that when you subscribe to something, it will continue to maintain a subscription and if that fails, re-subscribe till that succeeds. There perhaps can be some delivery of a 'non-critical' error that caused the sub to fail, but isn't terminal to the overall subscription process. This should be done through a separate callback arguably...

There is no free'ing up resources in this model unless the application consciously calls `ShutdownSubscription`, which will terminate a subscription (and kill it conclusively, even if it has resubscriptions enabled). At which point, I question why there is a need to deliver a callback back to the very same application about termination of a subscription it just initiated...
