### ISSUE TITLE
`chip-tool` unable to generate proper invalid Manual Codes when changing Version string

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#18454]
#### Problem
When attempting to generate an invalid Manual Code onboarding payload where the Version string is invalid (i.e. version=2), `chip-tool` generated the same 11-digit manual code when Version=0 and when Version=2. According to the spec doc, these should differ.

![image](https://user-images.githubusercontent.com/80923273/168401809-1b4020d6-9d85-4cd5-be19-98639e99ff4e.png)

 #### Logs
While testing TE9, `TC-DD-3.16` and `TC-DD-3.17`, Step 2.a

`chip-tool` commit: `caa1d6baca5c662c65ac156564ff3dca6eea0fb3`
```
16-MacBook-Pro:connectedhomeip liam$ ./out/chip-tool/chip-tool payload generate-manualcode --version 0 --discriminator 0xF00 --setup-pin-code 20202021   --commissioning-mode 0 --allow-invalid-payload 1
[1652485107122] [13136:8212591] CHIP: [TOO] Manual Code: 34970112332
16-MacBook-Pro:connectedhomeip liam$ ./out/chip-tool/chip-tool payload generate-manualcode --version 2 --discriminator 0xF00 --setup-pin-code 20202021   --commissioning-mode 0 --allow-invalid-payload 1
[1652485114817] [13138:8212668] CHIP: [TOO] Manual Code: 34970112332
16-MacBook-Pro:connectedhomeip liam$ 
```

**Comment by vivien-apple** [comment]
The thing is that generating such a code is not possible with the current format of the manual code. The reason is that the encoding of the version + the 2 ms-bits of discriminator + the presence of pid/vid is encoded as a single digit.
The 2 ms-bits of discriminator are basically + the presence of pid/vid generates a number between 0-7.
A new "version" of the manual code will be visible by a single digit value of "8" or "9". But what it means in practice is that the way to encode  The 2 ms-bits of discriminator are basically + the presence of pid/vid generates will be different in such a way that it makes it possible to retrieve those + the version number, which is not at the moment with the specified encoding.

So if you want to get an invalid manual code that says the version is NOT the one specified you just need to replace the first digit (3 in your example) by "8" or "9" and see what happens.

Closing as I don't think there is a way to generate it properly and it is easy to specify a "new" version by just replacing the first digit of the manual code by 8 or 9.
Obviously that would affects the check digit (which is the last digit of the manual code) but one can just do a trial and error manual checks by replacing the last digit until the correct one is found. For example if you use the number from your example (34970112332) you can manually replace "3" by "8" and the last digit "2" by "1" (84970112331).

That said, this is interesting to note that currently the stack does not throw if you try to use a code that starts with "8" or "9"... I will open a PR for that.
