### ISSUE TITLE
[pre-sve] TC-I-1.1 AcceptedCommandList doesnot show command with id 0x01 and GeneratedCommandList doesnt shows command with id 0

### ISSUE THREAD

**Issue by PSONALl** [project-chip/connectedhomeip#18928]
#### Problem
 * expected behavior vs actual behavior
      -  TH should read the AcceptedCommandList attribute from the DUT and This list should include the mandatory commands (values 0x00, and 0x01) but the list has only values 0, 64
      - TH should read the GeneratedCommandList attribute from the DUT and This list should include the mandatory response command (value 0x00) but the list is null

  * system configuration :
        -  DUT used : ESP32 
        -  app use: all-clusters-app
        - chip-tool and DUT commit id : 425f1fb916ca154deeb75cd82cd5196778aba152 (pre-sve SHA)
    
 * logs
      - esp32: [esp32.txt](https://github.com/project-chip/connectedhomeip/files/8795732/esp32.txt)
      - chip-tool: [th.txt](https://github.com/project-chip/connectedhomeip/files/8795734/th.txt)

**Comment by PSONALl** [comment]
@cjandhyala this is a  cert blocker

**Comment by cjandhyala** [comment]
@PSONALl Based on the resolution #18929 , the test plan needs to be updated per the latest spec changes and the issue is not on SDK

**Comment by cjandhyala** [comment]
@PSONALl Based on the resolution https://github.com/project-chip/connectedhomeip/issues/18929 , the test plan needs to be updated per the latest spec changes and the issue on the SDK side is that per spec reference app should not have returned the AcceptedCommandList with 64. Since this is not optional command, I labeling this as spec compliance rather than a cert blocker 

![Screen Shot 2022-05-30 at 3 29 40 PM](https://user-images.githubusercontent.com/68604034/171064811-c6d93dbd-6e54-4c8e-9301-5c55935b587c.png)

**Comment by cjandhyala** [comment]
@PSONALl #18929 discussion, we need SDK to implement QRY feature, until then GeneratedCommandList shows null value.

**Comment by bzbarsky-apple** [comment]
QRY is not part of Matter, so the SDK behavior here is correct.
