### ISSUE TITLE
[TC-MC-1.9]Target Navigator Cluster-- feature-map value mismatch.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18934]
#### Problem
As per test plan [TC-MC-1.9] FeatureMap attribute showing value mismatch error when executed, DUT should
responds with feature map value 0 but currently DUT responding feature map value has 1.

 **expected behavior:-**  DUT should responds the feature map value as 0
  **actual behavior:-** DUT is responding the feature map value as 1

 **steps to reproduce:-** ./chip-tool  targetnavigator read  feature-map 1 1
**system configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP
Commit-ID:4d84a4a978ffc867a62b9b15423a9b70d9cb993e			
Dut application: tv-app
 
**Test-Plan screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/170964603-be7871c7-8e6d-4ff5-90a4-f29b38b7c721.png)

**Spec screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/170964701-c10a3f4f-7544-4f03-accf-59731394dc2c.png)

![image](https://user-images.githubusercontent.com/95841834/171007212-8e0e1a0e-0182-42d6-9c7e-6b8ceb6fe80f.png)

**PFA log:-**
[feature-map 1.9.txt](https://github.com/project-chip/connectedhomeip/files/8797285/feature-map.1.9.txt)

**Comment by tehampson** [comment]
This issue seems like it was introduced in commit https://github.com/project-chip/connectedhomeip/commit/b36e4a278e.

This has a very trivial fix as all that is need to be done is set the default value to 0 in the zap file and regen files. I did look over all the other featuremaps that were assigned to 0x0001 in the above commit, and it seems to be that Target Navigator Cluster is the only one that is incorrect. The other seems to be valid feature map bit 0, and when enabled they have the correct corresponding commands that it is supposed to accept and respond to in the zap file.

https://github.com/project-chip/connectedhomeip/pull/18962
