### ISSUE TITLE
Multiple event subscription using chip-tool is not working

### ISSUE THREAD

**Issue by ukatira** [project-chip/connectedhomeip#19203]
#### Problem
Trying to run TC-SU-2.7 Step 5
Commit : 131b13c8b5ccb49585069c743b530310301deddd

OTA-R and OTA-P Linux App commissioned to same fabric. 
Further chip-tool interactions:
chip-tool interactive start
otasoftwareupdaterequestor subscribe-event download-error 30 60 2 0
otasoftwareupdaterequestor subscribe-event state-transition 30 60 2 0
Trigger OTA query using
otasoftwareupdaterequestor announce-ota-provider 1 0 0 0 2 0 

Only seeing events from later subscription while there is a Subscription Liveness timeout.

[1654210624314] [17708:66070994] CHIP: [DMG] Subscription Liveness timeout with SubscriptionID = 0x26b94210, Peer = 01:0000000000000002

 #### Proposed Solution
Multiple event subscription should work using chip-tool

[multiple event.txt](https://github.com/project-chip/connectedhomeip/files/8836098/multiple.event.txt)

**Comment by bzbarsky-apple** [comment]
By default, establishing a subscription from node A to node B tears down existing such subscriptions.  So that second subscribe-event is killing the first subscription.

You can pass `--keepSubscriptions true` in chip-tool when doing a subscribe to override that behavior.

For this specific case, I believe you can also do
```
otasoftwareupdaterequestor subscribe-event-by-id "0,2" 30 60 2 0
```
to create a single subscription to both events.
