### ISSUE TITLE
[TC-BC-2.1] Removing all Binding entries does not remove accessory from control

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#19542]
#### Problem
When running `[TC-BC-2.1]`, Step 8, the result is unexpected in that clearing the binding entries does not cause the DUT=controller to receive "No Response" when turning TH1 accessory on. 

> 16-MacBook-Pro:connectedhomeip liam$ ./out/darwin-framework-tool/darwin-framework-tool onoff on 1 1
...
[1655155486273] [75251:3549211] CHIP: [DMG] 				StatusIB =
[1655155486273] [75251:3549211] CHIP: [DMG] 				{
[1655155486273] [75251:3549211] CHIP: [DMG] 					status = 0x00 (SUCCESS),
[1655155486273] [75251:3549211] CHIP: [DMG] 				},

The previous step asks for removing all entries from the binding list and that list is empty but the command `./out/darwin-framework-tool/darwin-framework-tool onoff on 1 1` still performs successfully when it should not

#### Test Case
[[TC-BC-2.1]  Binding Cluster Attributes [DUT-Controller] ](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/binding.adoc#421-tc-bind-21-binding-cluster-attributes-dut-controller) 

![image](https://user-images.githubusercontent.com/80923273/173454938-58435dfd-b076-4bf5-9f51-75674b12282a.png)

 #### Logs
[TC-BC-2.1 Logs.txt](https://github.com/project-chip/connectedhomeip/files/8894986/TC-BC-2.1.Logs.txt)

**Comment by bzbarsky-apple** [comment]
I assume this is about TC-BIND-2.1; I can't find TC-BC-2.1 anywhere.

This test plan is wrong.  I filed https://github.com/CHIP-Specifications/chip-test-plans/issues/1465

But fundamentally, this test plan as I think it intends to be written does not apply to darwin-framework-tool, because the Darwin framework does not implement a server binding cluster and does not plan to.
