### ISSUE TITLE
Session resumption broken in nrfconnect

### ISSUE THREAD

**Issue by msandstedt** [project-chip/connectedhomeip#20169]
#### Problem

Tested at this rev:

```
commit 31ddf98b8100c2388e731bc757526c41e288198e (origin/master, origin/HEAD)
Author: Boris Zbarsky <bzbarsky@apple.com>
Date:   Thu Jun 30 09:57:40 2022 -0400

    Assume external attributes that must be non-volatile actually are. (#20144)
```

If a controller sends valid Sigma1 containing session resumption information, the nrf will never retrieve its session resumption record and always responds with Sigma2.

A similar thing was observed with ESP32.  In the case of that platform, this resolved it: https://github.com/project-chip/connectedhomeip/pull/18604

 #### Proposed Solution

* Verify whether key length is breaking session resumption on nrfconnect as it had broken it on ESP32
* Make nrfconnect support longer kvstore keys
* OR refactor session resumption storage strategy to use shorter keys

**Comment by bzbarsky-apple** [comment]
@Damian-Nordic @kkasperczyk-no

**Comment by kkasperczyk-no** [comment]
The reason of this problem is that Zephyr KVS backend doesn't support processing `=` character that is used in the CASE session key name. In case of replacing this character with some other character resumption seems to be working fine. It will be fixed by @Damian-Nordic altogether with other changes related to the KVS and discovered during persistent storage audit.

**Comment by kkasperczyk-no** [comment]
It should be now fixed after https://github.com/project-chip/connectedhomeip/pull/20298 was merged.

**Comment by msandstedt** [comment]
@kkasperczyk-no ,

I'll give it a try!  Thanks!

**Comment by msandstedt** [comment]
I have not checked, but I'm presuming this is fixed since zephyr now passes the storage audit.
