### ISSUE TITLE
[TC-MF-1.9] Manual code command with the wrong pin code supposed to be failed, it causes a crash on the chip-tool side.

### ISSUE THREAD

**Issue by shgutte** [project-chip/connectedhomeip#20271]
Problem:
If we try the manual code command with the wrong pin code supposed to be failed, it causes a crash on the chip-tool side.

Actual Behavior :
Creating with chip stack locking error.

Expected Behavior:
It should fail with PASE session error message 

App used - lock app
Platform - Chip-tool - RPI-4, 8GB RAM
DUT - EFR32 + WF200 , EFR32 +RS9116
Network - Ble-wifi

Logs
[Device 1 chip-tool logs.txt](https://github.com/project-chip/connectedhomeip/files/9039857/Device.1.chip-tool.logs.txt)
[Device 2 chip-tool logs.txt](https://github.com/project-chip/connectedhomeip/files/9039858/Device.2.chip-tool.logs.txt)
[TC-MF-1.9_1 Device Logs.txt](https://github.com/project-chip/connectedhomeip/files/9039859/TC-MF-1.9_1.Device.Logs.txt)
:

**Comment by bzbarsky-apple** [comment]
It looks like we discovered a number of matching devices on the network, then when the command timed out (it's being run with a 3-second timeout) tried to shut down while we had not tried all the devices yet.

This landed us in `DeviceCommissioner::Shutdown` (this is presumably _after_ stopping the event loop), which then did `OnSessionEstablishmentError` and that led us to just try the next discovered address.  

Then we try to send a message and that fails the threading assert, probably because it's running on Linux where that detection was buggy until #20180.

So first of all, this should no longer crash with that assert on tip.

Second, we should not be trying to pair during shutdown.....
