### ISSUE TITLE
[Android]can not get PID &ProductName from Java

### ISSUE THREAD

**Issue by nicelyjust** [project-chip/connectedhomeip#20590]
#### Problem
after this #19514 commited, then unenable to get PID &ProductName from AndroidConfig

 #### Proposed Solution
support to get PID &ProductName from AndroidConfig

**Comment by kkasperczyk-no** [comment]
Unfortunately I didn't fix that, the first fix was also required, but the actual cause is different. The reason is that every platform or application that wants to use the different `DeviceInstanceInfoProvider` implementation than default needs to call `SetDeviceInstanceInfoProvider()`. As far as I know currently the ESP32 and nRFConnect do it and it works, but it should be also done for Android, Darwin, Linux, Tizen and Webos, as those one have platform implementation provided.

I wanted to fix that for those platforms on a platform layer to not call `SetDeviceInstanceInfoProvider()` for every particular example/app, but I had some problems with solving dependency errors and then had bunch of other work that didn't allow me to get back to it. I still remember this issue and I already discussed it with other Nordic folks (@ArekBalysNordic  specifically) to delegate fixing this to someone else due to my lack of time. Sorry for the delay.
