### ISSUE TITLE
[TC-DGWIFI-2.3] - packet-unicast-rx-count attribute shows some packets after the reset counts

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#20764]
**Problem:**

-  In Wifidiagnosic cluster [TC-DGWIFI-2.3] - packet-unicast-rx-count attribute shows some packets after the reset counts command.
-  After executing the reset count command need to check the attributes are really reseted or not .but while reading  packet-unicast-rx-count attribute it shows some packet,Actually as per spec the attributes are reseted to **"0"**.

**App used:** All-clusters-app
  **Dut used:** Raspi

 **Actual outcome:**
 PacketUnicastRxCount: 20

 **Expected outcome:**
 PacketUnicastRxCount: 0

**Commands used:**
```
./chip-tool wifinetworkdiagnostics reset-counts 1 0
./chip-tool  wifinetworkdiagnostics read packet-unicast-rx-count 1 0

```
**Spec reference:**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsWiFi.adoc#5-commands

**Logs for reference:**
[DGWIFI-2.3.txt](https://github.com/project-chip/connectedhomeip/files/9115266/DGWIFI-2.3.txt)

**Comment by bzbarsky-apple** [comment]
> Expected outcome:
> PacketUnicastRxCount: 0

That can't possibly be an expected outcome, because if nothing else the packets carrying the read have been received.  As has the ack for the response to the reset-counts command.  And probably other packets, if there's anything else on the network.

If there is absolutely not other traffic on the WiFi network, and no packet loss reading to retransmits, etc, etc,`PacketUnicastRxCount` might be 2 (one ack and one read).  But it will certainly never be 0.
