### ISSUE TITLE
Read/Subscribe handler eviction can put reporting engine in a bad state

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#21350]
#### Problem
When we evict Read/Susbcribe handlers, we call `Close()` on the handler.

This puts it into the `AwaitingDestruction` state, which means that in its destructor it does not call `OnReportConfirm` on the reporting engine.  If it was in the "awaiting report response" state before being evicted, we will fail to decrement `mNumReportsInFlight` and eventually we will stop being able to send reports at all, because we will think we have `CHIP_IM_MAX_REPORTS_IN_FLIGHT` in flight while we actually have none.

 #### Proposed Solution
Actually, receiving a non-StatusResponse message looks like it would have the same problem.  So maybe the right fix is actually to either eliminate the AwaitingDestruction state entirely and just have `Close` call OnDone, or do the `OnReportConfirm` bits in `Close` before transitioning to the `AwaitingDestruction` state?

@erjiaqing @mrjerryjohns @yunhanw-google

**Comment by mrjerryjohns** [comment]
We shouldn't actually move the `OnReportConfirm` logic to `Close` since it's possible to shut-down the handler by directly destroying it without calling `Close` (e.g `InteractionModelEngine::Shutdown`), so having the logic in the destructor I think is still the most right and safest thing.

We should just delete the `AwaitingDestruction` state since a) it's not used to check or guard any other API access and b) the destruction is fairly immediate and synchronous from the point that Close() is called.

**Comment by bzbarsky-apple** [comment]
> We shouldn't actually move the OnReportConfirm logic to Close 

I was not suggesting we move them.  I was suggesting we copy them, so we do it before we go into the AwaitingDestruction state, then in the destructor if we're still `IsAwaitingReportResponse()` we do it there too.

> We should just delete the AwaitingDestruction state

That works for me.

**Comment by bzbarsky-apple** [comment]
Oh, hmm.  I guess we actually did handle this correctly in that `MoveToState` has that copy of the `OnReportConfirm` logic, when leaving the `AwaitingReportResponse` state!

**Comment by mrjerryjohns** [comment]
That's not pretty. We should really fix that...
