### ISSUE TITLE
TC-DA-1.2 - Certification Type should be 1 or 2 but I am getting 0 in step 8.3

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#21578]
**Issue :** 
In step 8.3 we need to verify Certification Type which should be either  1 or 2 but I am getting 0 in TH log after commissioning, 
![image](https://user-images.githubusercontent.com/90545664/182543534-d1d493e0-5eaa-42c9-ae6d-f1a3c35dba1c.png)

Commit used : 97134c5bd28797e667bfbbc2bab61b9b723e92ae
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : linux platform
Dut application: all-clusters-app

**Test-plan reference:**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/deviceattestation.adoc#tc-da-1-2-device-attestation-request-validation-dut-commissionee

**Spec reference:**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/OperationalCredentialCluster.adoc#ref_CertChainTypeEnum

PFA Logs:
[Certificate.txt](https://github.com/project-chip/connectedhomeip/files/9248810/Certificate.txt)

**Comment by bzbarsky-apple** [comment]
Your spec reference is wrong.  The correct spec reference is https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/device_attestation/Certification_Declaration_Specification.adoc#ref_CertDecl ("6.3.1. Certification Declaration (CD) Format" in the full spec), which says:

> The certification_type field SHALL contain the type of certification for this CD, interpreted according to the following table:

* 0: used for development and test purposes
* 1: provisional - used for a device when going into certification testing, or to allow production and distribution to occur in parallel with certification (with potential software fixes yielding a higher SoftwareVersion which gets certification)
* 2: official - allocated after passing certification

So for all-clusters-app 0 is correct, because it's a test app, not a real device.  Just like for all-clusters-app a vendor id outside the `[0x0001 .. 0xFFF0]` range in the test plan is correct, because it's a test app, not a real device.

**Comment by bzbarsky-apple** [comment]
@cjandhyala
