### ISSUE TITLE
Need YAML support for validating constraint or null

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#21627]
Summary:
Need support for test steps where we need to check if a values is null, if the values is not null we need to validate its constraints
Effected tests:
TC-RH-2.1
TC-TMP-2.1
TC-FLW-2.1
Testplan screenshot:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/relativehumiditymeasurement.adoc#tc-rh-2-1-attributes-with-server-as-dut
![image](https://user-images.githubusercontent.com/102359958/182848935-401724db-0536-4175-bd96-6756499b9397.png)

**Comment by bzbarsky-apple** [comment]
@manjunath-grl I don't understand what the issue is.  For a nullable value min/max constraints always pass if the value is null.

That is, if you write this in the YAML:
```
  constraints:
      minValue: 1
      maxValue: 0xfffd
```
then the behavior as a function of the value will be:

* null: pass
* non-null, less than 1: fail
* non-null, greater than 0xfffd: fail
* non-null, otherwise: pass

**Comment by manjunath-grl** [comment]
@bzbarsky-apple thanks, we didn't know that constraints checks cover null values as well.
