### ISSUE TITLE
chip-tool: add more flexibility in PAA root folder selection

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#21681]
#### Problem
chip-tool currently can only select a PAA root folder by command line argument. This presents an integration problem in various existing certification tools since a large amount of calls in several scripts would need to be changed. Instead there is a need for more flexibility in specifying PAA root folder which only requires a backwards compatible change to chip-tool.

 #### Proposed Solution
The following to be applied to chip-tool if --paa-trust-store-path is not given:

    if ~/paa-root-certs exists use that
    else if environment variable PAA_ROOT_CERTS exists use that

**Comment by tcarmelveilleux** [comment]
Assigned to @kpschoedel, he may have time within the next few days. Otherwise we will reassign.

I would recommend against `~/paa-root-certs` -> this can be achieved by having `PAA_ROOT_CERTS` environment variable set to `~/paa-root-certs` in the shell's profile by default, which would avoid special casing.

**Comment by bluebin14** [comment]
yes, PAA_ROOT_CERTS should be sufficient
