### ISSUE TITLE
Rather That Removing Them, Time-/Processor-intensive Crypto Callbacks Should Be Instrumented in Crypto Code

### ISSUE THREAD

**Issue by gerickson** [project-chip/connectedhomeip#2197]
#### Problem
In the security manager, there exist two callbacks:

1. OnTimeConsumingCryptoStart
2. OnTimeConsumingCryptoDone

There is currently a [pull request outstanding](https://github.com/project-chip/connectedhomeip/pull/2196/files) to remove these.

The point of these callbacks is to callout and signal device- or platform-specific code that a time- and/or processor-intensive crypto operation is about to begin and that either power management modes should be altered accordingly and/or UI/UX should be triggered to indicate such an operation.

#### Proposed Solution
Since CHIP will surely involve time- and processor-intensive operations. Rather than removing these callbacks, these callbacks should be instrumented in time- and processor-intensive portions of CHIP crypto code to support such device- or platform-specific behavior.

/cc/ @andreilitvin

**Comment by andy31415** [comment]
We likely would want to do this as part of integrating the SPAKE2+ (and maybe others) bits into the WML port.

We may also want to consider how these callbacks are presented and stubbed out, with ideas like:
   - have a 'app overrides' namespace or finding a different way to group such methods
   - consider using weak linkage for stubs, so that code always compiles but the app has the option of overriding as needed
   - consider a callback approach instead of free functions - slightly more expensive but easier to group.
