### ISSUE TITLE
GitHub storage is full

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#2285]
#### Problem
Looks like bloat reports are bloating our storage :) 

 #### Proposed Solution
Can we just keep the last X bloat reports around?

**Comment by andy31415** [comment]
I believe the issue is build packages: we currently keep 30 days work of 'master build' packages and build packages are quite large (10s of MB per platform and we keep adding).

I will switch it to 'keep last N' rather than time-based, with the hope that people sync reasonably frequently to get a bloat report.

**Comment by andy31415** [comment]
I updated the script and test-ran it (although a bit too aggressive and now we have 20 binaries ... will need to wait for it to go to 80 again).

@woody-apple  is there a way for us to check what the current storage usage is?
