### ISSUE TITLE
[BUG] minimalMdns repeats announcements/replies in violation of RFC6762

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#23360]
### Reproduction steps

1. Commission a device using minimal mDNS as the backend (e.g. even all-clusters-app)
2. Capture traffic during commissioning

### What is expected:
- DUT announces 1 time on each interface where we care to listen, one time on IPv4 (if enabled), one time on IPv6 (if enabled). The source address on IPv6 should be the link-local address since mDNS is on-link.
  - In theory we should do probing, but this is highly complex/stateful and we are unlikely to collide, so we don't
- DUT responds to any query *only on the interface where it was received* and *only on the IP generation where it was received*, with a single response. Ex: receiving an IPv6 query on wlan0 --> only respond on IPv6 mDNS on wlan0.

### What is observed

During announcement (unsollicited announcements when Advertise is done in DnsSd server) on an IPv4-disabled device:
![image](https://user-images.githubusercontent.com/1313847/198089168-301ff820-8973-432d-99a2-01ed66e9975c.png)

We can see that (forget about the timestamp, pcap device had a bug in software. The timestamps were verified at source to be "together". Instead of 1 IPv6 announcement, we see 8.

### Bug prevalence

100%

### GitHub hash of the SDK that was being used

9c3fedab6c7fcd7a6856782ffea31ee301aec91a

### Platform

core

### Areas to validate

- [ ]  DUT announces 1 time on each interface, one time on IPv4 (if enabled), one time on IPv6 (if enabled). The source address on IPv6 should be the link-local address since mDNS is on-link.
- [ ] DUT responds to any query *only on the interface where it was received* and *only on the IP generation where it was received*, with a single response. Ex: receiving an IPv6 query on wlan0 --> only respond on IPv6 mDNS on wlan0.

**Comment by andy31415** [comment]
I am trying to reproduce this. Currently I am checking using minmdns examples (server and client) on linux since their behaviour should be the same as embedded and it is faster to debug. What I see is:

- On multicast queries only a single reply is sent. Everything else is throttled and not replied to even though the server considers it
- Unicast queries seem to be responded to many times: client attemts a query for every interface + ip address type combination, server seems to reply a LOT more. I believe a single broadcast is received many times: I changed the code to send a single broadcast and I received 8 replies on my network (I have multiple network cards and ipv4/ipv6 addresses on each).

**Comment by andy31415** [comment]
I believe the issue we have is that the code attempts to listen on multiple interfaces, however a single listen should be sufficient: one for IPv4 and one for IPv6. Otherwise even though we attempt to bind UDP endpoints to specific interfaces, we will still receive all queries over every listen interface.
