### ISSUE TITLE
Using the examples with Google Home

### ISSUE THREAD

**Issue by guylevin** [project-chip/connectedhomeip#23555]
Hello  
  
I've tried some of the examples using ESP32_DevkitC_V4 and Google Home  
  
The board is flashed correctly, and I'm able to pair it afterward using the Google Home app  
 
I can see in the serial monitor and also in the router that the board is connected to the wifi  
  
I can see the device in the google home app  

I've also set it up in the google home console.

But when I'm trying to switch on the light (for example, in the lighting app) using the google home app, it just says, "something went wrong"  

I don't see any logs related to it in the serial console

I've tried the light-switch-app, the lighting-app, lock-app and the all-clusters-app

Verified with ESP32_C3_DevKitM as well

I have google home displays on the preview program, v.8.2.
I can see many announcements that these devices will be used as a matter hub, but I'm not sure if they are already

**Comment by guylevin** [comment]
please delete

**Comment by ZH-neutron-star** [comment]
please, how do u solve this issue ?

**Comment by guylevin** [comment]
@ZH-neutron-star I didn't yet

**Comment by devtn97** [comment]
I think google home use matter old version, I build new chiptool to control it work.

**Comment by tcarmelveilleux** [comment]
Matter support for Google Home ecosystem is still under public preview and the final release is upcoming. Until there is official support in Google Home app for the final Matter 1.0, some usecases have limited explanations or error handling.

Issues with pre-release Google Home cannot be addressed in SDK. Closing issue since it is not related to SDK directly.
