### ISSUE TITLE
[Documentation] Links in /REVIEWERS.md Broken

### ISSUE THREAD

**Issue by LawrenceQuarshie** [project-chip/connectedhomeip#23767]
### Documentation issues

```bash
1. The reviewers groups in the /REVIEWERS.md file are broken. Clicking on each one of them leads to a 404 page.
```

### Anything else?

https://github.com/orgs/project-chip/teams/reviewers-apple

**Comment by LawrenceQuarshie** [comment]
Hello @bzbarsky-apple 

Please links are still broken.

Is there anything that can be done?

Thank you.

**Comment by bzbarsky-apple** [comment]
@LawrenceQuarshie The links are not broken.  You're getting 404 because that's what github does if you load a github page that you don't have permissions to view.

https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams#team-visibility says:

> People who are not members of the organization cannot view any teams.

In practice, if you create a PR, it will get reviewed; a number of people look for incoming PRs (though this time of year there's a lot of vacation going on, of course).

**Comment by LawrenceQuarshie** [comment]
Thank you very much @bzbarsky-apple 

This is my first contribution to open source so pardon if things didn't go like expected.

I am learning and I am going to get better with time.

**Comment by bzbarsky-apple** [comment]
@LawrenceQuarshie No need to apologize!  The github behavior for showing 404 for "permission denied" (which is basically so people can't check whether things they don't have access to exist by getting a different error) is _very_ non-obvious.

**Comment by LawrenceQuarshie** [comment]
That is well noted @bzbarsky-apple .
