### ISSUE TITLE
Address review comments on PR #24539

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#24553]
1. Instead of `codegen-cpp-only` do something like `--generator codegen --codegen cpp-app`
2. Instead of messing with the filter, just avoid adding `CodegenJavaPregenerator` to the list if codegen is `cpp-app`.

**Comment by andy31415** [comment]
We may also just want to extend the `--generator` format to standardize on some separator. Like accept `codegen` but also `codegen:java` or `codegen:cpp-app` to control the internal generator list.

In the PR review I am basically asking to not special case cpp-app but make it more generic (and also control generator array instead of passing down this to accept methods since the intent seems to control the generator)
