### ISSUE TITLE
[Feature] [ESP32] Support esp-idf v5.0 release

### ISSUE THREAD

**Issue by shubhamdp** [project-chip/connectedhomeip#24576]
### Feature description

[ESP-IDF Release v5.0](https://github.com/espressif/esp-idf/releases/tag/v5.0) is out some time back and it is not supported in the SDK.

This issue is to track the progress for supporting esp-idf v5.0 alongside esp-idf v4.4.3

### Platform

esp32

### Anything else?
- [x] examples/lighting-app/esp32
- [x] examples/all-clusters-app/esp32
- [x] examples/all-clusters-minimal-app/esp32
- [x] examples/bridge-app/esp32
- [x] examples/light-switch-app/esp32
- [ ] examples/ota-provider-app/esp32
- [ ] examples/ota-requestor-app/esp32
- [ ] examples/temperature-measurement-app/esp32
- [ ] examples/lock-app/esp32
- [ ] examples/chef/esp32

**Comment by vindicatorr** [comment]
Just adding myself to this. I thought I was going crazy because I thought I had commented on this sort of thing, and I was looking for references of myself as author. Only did I finally see my comment as "commenter" (https://github.com/project-chip/connectedhomeip/issues/17239#issuecomment-1368643196)

I only mention it again because I just encountered it again regarding the error "format \<...\> expects argument of type \<...\>, but argument \<#\> has type '\<type\>' {aka ''\<definition\>'}". I've got to put that in my notes so I don't have to go checking the function of my mind.

**Comment by dhrishi** [comment]
@shubhamdp Please update the apps which are now supported. If everything is complete, close the issue.

**Comment by shubhamdp** [comment]
@dhrishi updated the supported apps. I will put up one more PR to support remaining apps and once that is merged, I'll close the issue
