### ISSUE TITLE
How to set Default Delegate?

### ISSUE THREAD

**Issue by avpmax** [project-chip/connectedhomeip#24721]
I'm working with a WindowCoveringDevice cluster on esp32. 
Since the GoToLiftPercentage command is not created by default, 
I created it as a custom command and it worked fine. 
However, since commands such as UporOpen, DownorClose, and Stop are created by default and cannot be deleted, 
custom commands cannot be substituted. 
So I want to implement the callback of the corresponding commands using SetDefaultDelegate. 
However, delegate cannot be set because emberAfFindClusterServerEndpointIndex always returns 0xFFFF. 

What is the procedure for registering SetDefaultDelegate?

**Comment by bzbarsky-apple** [comment]
> Since the GoToLiftPercentage command is not created by default, I created it as a custom command and it worked fine.

How did you "create it as a custom command"?  The command is optional, but can just be enabled in the ZAP configuration.  Is that what you did?  If not, what exact thing did you do, @avpmax ?

> However, since commands such as UporOpen, DownorClose, and Stop are created by default and cannot be deleted,
custom commands cannot be substituted.

"substituted" in what sense?  UpOrOpen is a mandatory command, so it has to be implemented, yes...

>  However, delegate cannot be set because emberAfFindClusterServerEndpointIndex always returns 0xFFFF.

That's because it's looking for Channel clusters for some reason, not Window Covering clusters.  https://github.com/project-chip/connectedhomeip/pull/24730 should fix that; nice catch!
