### ISSUE TITLE
Replace SEND_COMMAND_UNICAST_TO_BINDINGS

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#2504]
SEND_COMMAND_UNICAST_TO_BINDINGS has calls to:
emberAfSendCommandUnicastToBindingsWithCallback
and 
emberAfSendCommandUnicastToBindings

which are not implemented anywhere

**Comment by bzbarsky-apple** [comment]
> `emberAfSendCommandUnicastToBindingsWithCallback`
> `emberAfSendCommandUnicastToBindings`

Those live in `src/app/util/client-api.c` but someone commented them out at some point...  That said, those end up calling functions that we don't have implemented yet; might need to either pull in more stuff from `af-main-common.c`, `af-main-host.c`, `af-main-soc.c` or reimplement this on top of CHIP stuff.   Which doesn't exist yet, because CHIP doesn't really have a concept of bindings yet....  We do have a binding-table thing in `src/app/util` now, but apart from groups-server cluster I don't think anything else does anything with it yet.  

@shana-apple does the code you're adding use the binding table?
