### ISSUE TITLE
Flash script built inside Docker doesn't work outside Docker

### ISSUE THREAD

**Issue by szatmz** [project-chip/connectedhomeip#2512]
#### Problem
Images (e.g. nrf5 examples) built inside docker cannot be flashed likely because the flash script does not have access to USB.

 #### Proposed Solution
Open USB up in docker image(s).

**Comment by kpschoedel** [comment]
I don't know whether anything can be done about Docker permissions, but the flash script can be revised so that it works outside docker. The path names in it are currently absolute (i.e. with respect to the Docker container) so they make no sense outside. Changing them to be relative to the output directory and/or flash script (currently the same) would make it usable outside the container, and would also make sense for a CI configuration that might have building and flashing on different machines.

**Comment by kpschoedel** [comment]
Looked at Docker a bit and it seems there is no good way to flash from _inside_ the container (portable, reliable, secure… pick at most one) though an individual developer may find `--device` or `--device-cgroup-rule` options work well enough for their case.

The current plan is for building to copy all files necessary for flashing into the output directory and remove any references to the build tree from the flashing scripts, so that flashing natively after building in a container works smoothly.
