### ISSUE TITLE
[Feature] I want a smaller libchipcontroller.so for android 

### ISSUE THREAD

**Issue by luobosu** [project-chip/connectedhomeip#26134]
### Feature description

...
I have remove the symbol tables of libchipcontroller.so , but it still too large , about 6MB ,   Anyone can help me to optimize it ?

For android jni libs.

### Platform

android

**Comment by joonhaengHeo** [comment]
https://github.com/project-chip/connectedhomeip/issues/25556

**Comment by yunhanw-google** [comment]
@luobosu could you retry with latest code, this issue should be resolved. Since we decouple generated ChipCluster, please use generic IM Java/JNI API listed in https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/src/chip/devicecontroller/ChipDeviceController.java#L887, you could refer latest android chip-tool for the usage where we have used the generic IM Java/JNI API across. thanks
