### ISSUE TITLE
[Feature] Synchronize device status automatically 

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#26204]
### Feature description

...
I am utilizing the chip-tool to operate my nano strip device and enable the interactive mode. Nevertheless, when I power off the device manually, there is no notification informing me that the device is turned off. May I know which command I should use to receive this notification？

### Platform

other

**Comment by bzbarsky-apple** [comment]
You could subscribe to Shutdown events on the relevant node.  But those are not guaranteed to be delivered, of course, since the packets could be lost and cannot be re-transmitted because the device is shut down.

And if you have a subscription and the device stops sending the max-interval heartbeat packets, the subscription will eventually error out, of course, and you will then know that it's not talking to you.
