### ISSUE TITLE
[BUG] [chip-tool] cannot build for armhf (32bit ARM)

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#26466]
### Reproduction steps

I tried cross build for armhf on Ubuntu 22.04 x86_64.

As a prerequisite, I added `ports.ubuntu.com` to `/etc/apt/sources.list.d/ports_armhf.list`.

```bash
$ sudo dpkg --add-architecture armhf
$ sudo apt update
$ sudo apt install crossbuild-essential-armhf
$ sudo apt install libssl-dev:armhf
$ sudo apt install libglib2.0-dev:armhf
$ cd ${MATTER_SDK}
$ source scripts/activate.sh
$ cd examples/chip-tool
$ gn gen out/debug --args='target_os="linux" target_cpu="arm"'
$ ninja -C out/debug
```

**LOG**
[chip-tool-armhf-build.log](https://github.com/project-chip/connectedhomeip/files/11437723/chip-tool-armhf-build.log)

> /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h

I set `target_cpu="arm"`, but ninja accessed `x86_64-linux-gnu` directory.

and it maybe root cause is 64bit variable.

Can I resolve it?

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 4088a77f557e8571a39338fad51a1d8eb0131d79 (HEAD, tag: v1.0.0.2)

### Platform

other

### Anything else?

Host OS : Ubuntu 22.04

**Comment by mmt-10** [comment]
resolve it

```bash
$ export PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig"
```

**Comment by bzbarsky-apple** [comment]
Right, the glib path comes from pkg-config, and that will do what you tell it to do....

**Comment by xlfdan** [comment]
@mmt-10 , can you show the full content of ports_armhf.list and sources.list files? Thank you very much.

**Comment by xlfdan** [comment]
ubuntu@ubuntu-VM:~$ sudo apt install libssl-dev:armhf

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:



The following packages have unmet dependencies:

 libssl1.1:armhf : Depends: libc6:armhf (>= 2.28) but it is not going to be installed

E: Unable to correct problems, you have held broken packages.

ubuntu@ubuntu-VM:~$ 

ubuntu@ubuntu-VM:~$ sudo apt install libssl1.1:armhf

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:



The following packages have unmet dependencies:

 libssl1.1:armhf : Depends: libc6:armhf (>= 2.28) but it is not going to be installed

E: Unable to correct problems, you have held broken packages.

ubuntu@ubuntu-VM:~$ 

ubuntu@ubuntu-VM:~$ sudo apt install libc6:armhf

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:



The following packages have unmet dependencies:

 apt : Depends: adduser but it is not going to be installed

       Depends: gpgv or

                gpgv2 but it is not going to be installed or

                gpgv1

       Depends: libapt-pkg6.0 (>= 2.4.6) but it is not going to be installed

       Depends: libc6 (>= 2.34) but it is not installable

       Depends: libgcc-s1 (>= 3.3.1) but it is not going to be installed

       Depends: libgnutls30 (>= 3.7.0) but it is not going to be installed

       Depends: libseccomp2 (>= 2.4.2) but it is not going to be installed

       Depends: libstdc++6 (>= 11) but it is not going to be installed

       Depends: libsystemd0 but it is not going to be installed

       Recommends: ca-certificates but it is not going to be installed

 base-files : PreDepends: awk

              Depends: libc6 (>= 2.34) but it is not installable

 base-passwd : Depends: libc6 (>= 2.34) but it is not installable

               Depends: libdebconfclient0 (>= 0.145) but it is not going to be installed

 bash : PreDepends: libc6 (>= 2.34) but it is not installable

        PreDepends: libtinfo6 (>= 6) but it is not going to be installed

 bsdutils : PreDepends: libc6 (>= 2.34) but it is not installable

            PreDepends: libsystemd0 but it is not going to be installed

            Recommends: bsdextrautils

 coreutils : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed

             PreDepends: libattr1 (>= 1:2.4.44) but it is not going to be installed

             PreDepends: libc6 (>= 2.34) but it is not installable

             PreDepends: libgmp10 (>= 2:6.2.1+dfsg) but it is not going to be installed

             PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed

 dash : PreDepends: libc6 (>= 2.34) but it is not installable

 debianutils : PreDepends: libc6 (>= 2.34) but it is not installable

 diffutils : PreDepends: libc6 (>= 2.34) but it is not installable

 dpkg : PreDepends: libbz2-1.0 but it is not going to be installed

        PreDepends: libc6 (>= 2.34) but it is not installable

        PreDepends: liblzma5 (>= 5.2.2) but it is not going to be installed

        PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed

        PreDepends: libzstd1 (>= 1.4.0) but it is not going to be installed

        PreDepends: zlib1g (>= 1:1.1.4) but it is not going to be installed

 e2fsprogs : PreDepends: libblkid1 (>= 2.36) but it is not going to be installed

             PreDepends: libc6 (>= 2.34) but it is not installable

             PreDepends: libcom-err2 (>= 1.43.9) but it is not going to be installed

             PreDepends: libext2fs2 (= 1.46.5-2ubuntu1.1) but it is not going to be installed

             PreDepends: libss2 (>= 1.38) but it is not going to be installed

             PreDepends: libuuid1 (>= 2.16) but it is not going to be installed

             Depends: logsave

             Recommends: e2fsprogs-l10n but it is not going to be installed

 findutils : PreDepends: libc6 (>= 2.34) but it is not installable

             PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed

 grep : PreDepends: libc6 (>= 2.34) but it is not installable

        PreDepends: libpcre3 but it is not going to be installed

 gzip : PreDepends: libc6 (>= 2.34) but it is not installable

 hostname : PreDepends: libc6 (>= 2.34) but it is not installable

 init : PreDepends: systemd-sysv

 libc-bin : Depends: libc6 (> 2.35) but it is not installable

            Depends: libc6 (< 2.36) but it is not installable

 libc6:armhf : Depends: libgcc-s1:armhf but it is not going to be installed

               Depends: libcrypt1:armhf (>= 1:4.4.10-10ubuntu4) but it is not going to be installed

               Recommends: libidn2-0:armhf (>= 2.0.5~) but it is not going to be installed

 libcrypt1 : Depends: libc6 (>= 2.25) but it is not installable

 login : PreDepends: libaudit1 (>= 1:2.2.1) but it is not going to be installed

         PreDepends: libc6 (>= 2.34) but it is not installable

         PreDepends: libpam0g (>= 0.99.7.1) but it is not going to be installed

         PreDepends: libpam-runtime but it is not going to be installed

         PreDepends: libpam-modules but it is not going to be installed

 ncurses-bin : PreDepends: libc6 (>= 2.34) but it is not installable

               PreDepends: libtinfo6 (>= 6.3) but it is not going to be installed

 perl-base : PreDepends: libc6 (>= 2.35) but it is not installable

 sed : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed

       PreDepends: libc6 (>= 2.34) but it is not installable

       PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed

 shim-signed : Depends: grub-efi-amd64-signed but it is not going to be installed or

                        grub-efi-arm64-signed but it is not installable

               Depends: grub2-common (>= 2.04-1ubuntu24)

               Depends: mokutil (>= 0.3.0+1538710437.fb6250f-0ubuntu2) but it is not going to be installed

               Depends: sbsigntool

               Recommends: secureboot-db but it is not going to be installed

 sysvinit-utils : Depends: libc6 (>= 2.34) but it is not installable

 tar : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed

       PreDepends: libc6 (>= 2.34) but it is not installable

       PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed

 util-linux : PreDepends: libaudit1 (>= 1:2.2.1) but it is not going to be installed

              PreDepends: libblkid1 (>= 2.37.2) but it is not going to be installed

              PreDepends: libc6 (>= 2.34) but it is not installable

              PreDepends: libcap-ng0 (>= 0.7.9) but it is not going to be installed

              PreDepends: libmount1 (>= 2.37.2) but it is not going to be installed

              PreDepends: libpam0g (>= 0.99.7.1) but it is not going to be installed

              PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed

              PreDepends: libsmartcols1 (>= 2.34) but it is not going to be installed

              PreDepends: libsystemd0 but it is not going to be installed

              PreDepends: libtinfo6 (>= 6) but it is not going to be installed

              PreDepends: libudev1 (>= 183) but it is not going to be installed

              PreDepends: libuuid1 (>= 2.16) but it is not going to be installed

              PreDepends: zlib1g (>= 1:1.1.4) but it is not going to be installed

E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

ubuntu@ubuntu-VM:~$

**Comment by mmt-10** [comment]
I'm sorry, I had vacation.

Please refer to below quote.
`ports_armhf.list` is here.

However, I gave up on cross-build.
because, I cannot resolve the library(glibc3.0 and etc) dependencies for the target board.
If you can resolve the library dependencies, please let me know.

> deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse
> deb-src [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse
> 
> deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse
> deb-src [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse
> 
> deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse
> deb-src [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse
> 
> deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse
> deb-src [arch=armhf] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse
>
