### ISSUE TITLE
[BUG] CASE session establishment is disabled after ScheduleWork fails in WorkHandler

### ISSUE THREAD

**Issue by wqx6** [project-chip/connectedhomeip#26737]
### Reproduction steps

The CASE session establishment is disabled after the `ScheduleWork` fails in `WorkHandler` and the device doesn't send the status report for sigma3. Then the device can never be reachable over CASE any more. Related to #26280.

The log:
[esp32_logs.txt](https://github.com/project-chip/connectedhomeip/files/11540658/esp32_USB5_logs.txt)

### Bug prevalence

Sometimes

### GitHub hash of the SDK that was being used

8f66f4215bc0708efc8cc73bda80620e67d8955f

### Platform

esp32

**Comment by bzbarsky-apple** [comment]
It's not 100% clear what we can do in that situation, short of timing out the async processing after some point, but "bricking" the device is not great either.

The real question is: why is ScheduleWork failing? @wqx6 all sorts of things will work wrong if async work can't be scheduled.

**Comment by wqx6** [comment]
The reason of ScheduleWork failing is that the event queue is full at that time. Looks like the `LwIPReceiveUDPMessage()` posts so many messages to event queue that the event queue is not enough for Sigma3 handling ScheduleWork.

**Comment by bzbarsky-apple** [comment]
OK, makes sense.

So in practical terms, what are the options there?  We could try again, but that requires scheduling something on the background-thread event loop to try again (is that separate from the main one?).

Obviously reducing the LwIPReceiveUDPMessage flooding would be helpful too.  I wonder whether we can have it start dropping messages before it fills up the event queue so that we guarantee we don't starve other things too much....

But fundamentally, if scheduling to the event loop does not work, a lot of things can get "stuck" because they have no way to progress.  :(

**Comment by mlepage-google** [comment]
Seems like it would be good if UDP messages didn't consume the last queue slot, or at were perhaps limited to a total number.
