### ISSUE TITLE
android: remove use of shared libc++

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#2680]
Middleware should not use shared libc++ as this can cause compatibility issues. We should instead link libc++ statically (our use of libc++ should be really minimal anyway).

- [ ] Hide all dynamic symbols except JNI_OnLoad and use RegisterNatives to hook up native code to JNI
- [ ] Compile with -static-libstdc++

**Comment by mspang** [comment]
@vidhis88

**Comment by andy31415** [comment]
NDK generally states 'only use static libc++ if you have exactly one shared library' which is not currently the case for CHIP.

Trying with 'none' if we use no C++ except new/delete could be an option if we really use no C++. Unsure if we can in any way hide all dynamic symbols. Especially since new/delete would be public and NDK describes allocating in one so and freeing in another as being one of the potential dangers.
