### ISSUE TITLE
[Question] Some questions about multi-admins/fabrics 

### ISSUE THREAD

**Issue by IcyWaterDL** [project-chip/connectedhomeip#26858]
1. Can I add multiple admins to one node in the same fabric?
2. Help me differentiate between multi-admins and multi-fabrics, please.

**Comment by bzbarsky-apple** [comment]
> Can I add multiple admins to one node in the same fabric?

Yes.  Just set up the ACLs on the node accordingly.

> Help me differentiate between multi-admins and multi-fabrics, please.

A "fabric" is a collection of nodes that can talk to each other, because they have a shared root of trust and can use the CASE protocol to set up an encrypted connection.  A node can be in multiple fabrics by having multiple operational certificates.

An "admin" is a node that has been granted administrative privileges on some other node, via the ACLs set there.

You can have multiple admins all on the same fabric, if you set up your ACLs that way.  Or you could remove all the admin ACLs and have no admins at all, though that's generally a bad idea.

**Comment by IcyWaterDL** [comment]
can i add other matter controller into the same fabric?

**Comment by bzbarsky-apple** [comment]
> can i add other matter controller into the same fabric?

Yes, as long as all the controllers involved have operational certificates chaining up to the same root.

**Comment by IcyWaterDL** [comment]
> > can i add other matter controller into the same fabric?
> 
> Yes, as long as all the controllers involved have operational certificates chaining up to the same root.

Can you give me some instructions on how to deploy it?
