### ISSUE TITLE
[Feature] Control Matter End Device Remotely 

### ISSUE THREAD

**Issue by nguyenhuy5997** [project-chip/connectedhomeip#26942]
### Feature description

Case 1:
Here we have 1 Smart Phone run Matter Controller, 1 Smart Speaker run Matter Controller, 1 Cloud and some Matter End Devices.
First, I use Smart Phone for commissioning Matter End Device into a Fabric. All gonna well. 
Now we want to control Matter End Device remotely. We know that Cloud will send command to Smart Speaker, then Smart Speaker will control Matter End Device via Matter protocol. But the Smart Speaker and Matter End Device are not in the same Fabric then we can not control Matter End device. 
Case 2:
Here we have 2 or more Smart Phone run Matter Controller with the same Smart home account, some Matter End Devices.
First, I use smart phone 1 for commissioning Matter End device into Fabric 1. All gonna well like case 1 
We want Smart phones with the same Smart home account are able to control Matter End Device in that account (like what we have seen in Smart Home ecosystem today). But likely Case 1, only Smart Phone 1 can control Matter End Device and the other Smart Phones are not able to do so because they are not in the same Fabric.
Can you guide me the flow to do this features? i know i can open commissioning window again but this will be terrible if there are hundred devices in the same account

### Platform

all

**Comment by bzbarsky-apple** [comment]
> But the Smart Speaker and Matter End Device are not in the same Fabric then we can not control Matter End device.

Right, so either the Smart Speaker needs to create its own fabric and commission the End Device into that, or the Smart Speaker should be on the same fabric as the Smart Phone in your example (and the Smart Phone) should set the ACLs on the End Device to allow the Smart Speaker to access it.

> the other Smart Phones are not able to do so because they are not in the same Fabric

Why isn't the second phone in the same fabric?  If they're tied to the same account, it seems like the right thing to do is to tie the fabric _to that account_, no?  So that's what you should do.  Certainly that's what Apple Home is doing.
