### ISSUE TITLE
Chip-tool has to be implemented for newly added clusters.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27165]
**Chip-tool command has to be implemented for below mentioned clusters:**
1. Dishwasher Mode Select Cluster.
2. Laundry Mode Select Cluster.
3. RVC Clean Mode Select Cluster.
4. RVC Operational State Cluster.
5. RVC Run Mode Select Cluster.
6. Refrigerator and Temperature Controlled Cabinet Cluster.
7. Washer Controls Cluster.

**Comment by bzbarsky-apple** [comment]
@Survensa please _always_ list the SHA involved.  

* The mode select clusters you list have been supported in chip-tool since https://github.com/project-chip/connectedhomeip/pull/26508 merged.  This includes what I suspect you mean by "Refrigerator and Temperature Controlled Cabinet Cluster".
* RVC Operational State is being added in https://github.com/project-chip/connectedhomeip/pull/26989
* Washer Controls has been supported in chip-tool since https://github.com/project-chip/connectedhomeip/pull/26702 merged.

**Comment by Survensa** [comment]
Verified with Master commit : 40fb7c246671e9d37ca8bb2cfbf37f81c1509334	

The only pending to be reflected in the chip-tool command is the RVC Operational State Cluster @bzbarsky-apple

**Comment by bzbarsky-apple** [comment]
Yes, that's why that PR is linked to this issue.
