### ISSUE TITLE
Decouple generated java/jni API from android chip-tool

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#27398]
generated java/jni API for IM is too big, we need to decouple it and fully use the generic java/jni IM API.

**Comment by joonhaengHeo** [comment]
@yunhanw-google 

I add feature for decoupling generated API.
But, Android Chip-tool can not disable this feature.
Because ChipClusters class is still used in "Cluster Interaction Tool" function.

A complete separation for the completion of this issue requires the following:

1. Addition of API that can change parameters used for each Command and Write Attribute to TLV.
(Of course, I know that there is a TLV parse library, but I think I need to find a way to do it without hardcoding as in the example below.)

https://github.com/project-chip/connectedhomeip/blob/a9773c943efd9c2dd840bad17b859c31a95ebb3c/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/OpCredClientFragment.kt#L111

2. Added API for TLV Docoding. This fix has been added to the PR.

Any other opinions?
