### ISSUE TITLE
[BUG] EpochStartTime on GroupKeyManagement

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#28672]
### Reproduction steps

Is this correct behavior? The spec says you can null it, but then shouldn't 0 work?  And that error code is not very good.

It I set EpochStartTime to zero it gives "status = 0x85 (INVALID_COMMAND),"

groupkeymanagement key-set-write {"groupKeySetID": 42, "groupKeySecurityPolicy": 0, "epochKey0": "d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 0,"epochKey1": null, "epochStartTime1": 0,"epochKey2": null, "epochStartTime2": 0 } 1 0

--------------------------
But if I set it to 1, it works.

groupkeymanagement key-set-write {"groupKeySetID": 42, "groupKeySecurityPolicy": 0, "epochKey0": "d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 1,"epochKey1": null, "epochStartTime1": 0,"epochKey2": null, "epochStartTime2": 0 } 1 0 

### Bug prevalence

always

### GitHub hash of the SDK that was being used

5b4f8004662d00bdb111367fec7d3ea978c23372

### Platform

core

**Comment by bzbarsky-apple** [comment]
Null is in fact not allowed here, per spec.

For the rest, see https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7368 which clarified in the spec that 0 is not allowed here, precisely because 1.0 SDK does not allow it.  Which was a bug, but at this point the easiest path to interop is to just make it clear it's disallowed.
