### ISSUE TITLE
[BUG] Android matter sdk setFabricId does not accept values which touch twos compliment

### ISSUE THREAD

**Issue by maurycyw** [project-chip/connectedhomeip#28696]
### Reproduction steps

Using an example fabric id: `d5f9b903418fda11`, I am unable to set the fabric id on the controller params since it only accepts a "signed" Long as a parameter. This fabric id can be parsed as an unsigned Long but when converting to a Long it becomes a negative value and fails the sdk check:
```
public Builder setFabricId(long fabricId) {
        if (fabricId < 1L) {
            throw new IllegalArgumentException("fabricId must be > 0");
        } else {
            this.fabricId = fabricId;
            return this;
        }
}
```
Repro steps:

1. Try to set a valid fabric id with a value greater than `7FFF_FFFF_FFFF_FFFF` on the controller parameters.

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

8f66f4215bc0708efc8cc73bda80620e67d8955f

### Platform

android

**Comment by yunhanw-google** [comment]
I think we should consider to update with Long instead of long.
for example, Long l1 = Long.parseUnsignedLong("d5f9b903418fda11");

I think this issue happens in several place with uint64_t in android controller.
both EventNumber and FabricId needs to be fixed since they are defined with
uint64_t EventNumber;
uint64_t FabricId;

**Comment by yunhanw-google** [comment]
@joonhaengHeo do you have bandwidth to fix this issue?
