### ISSUE TITLE
examples/common/chip-app-server is in the wrong place...

### ISSUE THREAD

**Issue by rwalker-apple** [project-chip/connectedhomeip#2927]
#### Problem(s)
* examples/common/chip-app-server should really be part of CHIP as it is based completely on CHIP APIs and is needed by nearly every CHIP device.  Ultimately it should define an API for applications to consume/implement (i.e. an evolved onAttributeChangedCallback()).
* there is no README.md that explains what belongs in examples/common, which led to the above

 #### Proposed Solution(s)
* move files in common/chip-app-server to src/app and include in the CHIP library built there (no need for a subdir, can be just a pile of files in src/app)
* write a README.md for examples/common that says "stuff that's not CHIP-based nor CHIP-supplied, but examples like to use" (like glue for displays, etc.)

**Comment by kkasperczyk-no** [comment]
@rwalker-apple I hope #4158 may fix reported issue. I wasn't able to fully address your suggestions, because the src libs build dependencies. Chip-app-server files need to have src/platform and src/transport modules built, while platform needs src/app, so I created new src module named accessory. I think it might be good idea, as those files actually are CHIP accessory device specific and there is no need to build them on different device types.
