### ISSUE TITLE
[Android]Figure out how to generate android chip-tool with setting matter_enable_java_generated_api as false

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#29324]

**Comment by joonhaengHeo** [comment]
@yunhanw-google 
Currently, this feature cannot be disabled due to the code in the folder below in Android ChipTool.
https://github.com/project-chip/connectedhomeip/tree/master/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/clusterinteraction

Also, there was a history of trying to change it through the PR below, but it was not merged due to the content of the comment.
https://github.com/project-chip/connectedhomeip/pull/28467

**Comment by yunhanw-google** [comment]
decide not disabled since community is broadly using these generated API, we would replace the underneath implemenation with generic IM API
