### ISSUE TITLE
Very High CPU and Memory Utilization While Building the Chip Tool

### ISSUE THREAD

**Issue by VaishaliAvhale** [project-chip/connectedhomeip#29559]
### Reproduction steps

While building the chip tool (using 'ninja -C out/debug'), I faced open process termination or System Restart issues due to high CPU and memory utilization.

I have followed the chip-tool build steps from below document:
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/chip_tool_guide.md

System Specification:
Kernal: 6.2.0-26-generic
![Screenshot from 2023-10-04 12-27-17](https://github.com/project-chip/connectedhomeip/assets/65866467/1ec16722-587d-43ff-a280-759626cc7a5a)

CPU and Memory Utilization:
![Screenshot from 2023-10-04 15-59-10](https://github.com/project-chip/connectedhomeip/assets/65866467/10286ad1-dafa-4b77-bd31-ae4ea142c3ba)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

54a146018c1b042b347b04e1ff7b075903b55603 

### Platform

core

**Comment by bzbarsky-apple** [comment]
High CPU is normal; ninja is just trying to use all the compute available.

I expect your real issue is the memory.  It looks like you have 16GB of RAM available; do you have any swap configured @VaishaliAvhale ?  chip-tool linking is pretty memory-intensive...

That said, it's _possible_ that using `-j1` for `ninja` would help with the memory too.  It looks like `scripts/examples/gn_build_example.sh` (which I assume you are using if you are following the above-linked docs) does not have support for passing a `-j` argument to ninja.  But if you modify that script's last line to read `ninja -j1 -C ...`, does that help?

**Comment by VaishaliAvhale** [comment]
Swap is configured on my system, and its size is 2GB. While building the chip tool, it was getting filled. I have increased its size to 4GB, and now I'm able to successfully build the chip tool in a single go.

I also tried to build a chip tool using the -j4 argument it works too but it is a bit slower.
Thanks, @bzbarsky-apple.

**Comment by bzbarsky-apple** [comment]
Yeah, OK.  Needing >2GB to link is not great, but not surprising given how chip-tool is set up...
