### ISSUE TITLE
CHIP landing page reads: "Connected Home over IP {#mainpage}"

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#3022]
#### Problem
Looks like our last doxygen change added this tag, but it's also human visible on the main landing page. Can we fix this?

**Comment by vivien-apple** [comment]
> #### Problem
> Looks like our last doxygen change added this tag, but it's also human visible on the main landing page. Can we fix this?

That's kind of strange. This tag has been introduced on the 18th of September and is normally used to tell Doxygen to use this page as the main page. I have not changed it in the last Doxygen changes you refer to. I wonder if Github has changed something on their side since I can see the tag being visible on a few different Github pages (also on https://github.com/doxygen/doxygen/blob/master/src/doxygen.md) which is here since 8 years.
