### ISSUE TITLE
[1.3] RVC Clean Mode  Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#30488]
### Description:

- [ ]  **"OnMode"  is `OnOff` Feature dependent attribute. This feature is marked as X in conformance. (X means -   This is disallowed for the cluster derivation),  but it is reflecting in XML file.**

**Screenshot:**

![image](https://github.com/project-chip/connectedhomeip/assets/98016634/e0310a60-469f-4781-8c15-11926e8676df)

![image](https://github.com/project-chip/connectedhomeip/assets/98016634/7a539cd2-56ec-4492-bd7a-81b99a672274)

**Spec Reference:**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/device_types/RoboticVacuumCleaner.adoc#element-requirements

**XML Reference:**
https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/rvc-clean-mode-cluster.xml

**Comment by hicklin** [comment]
The required change in the spec to address this issue was made in [this PR](https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8637).

The required changes to the SDK following this spec change PR are tracked by [this issue](https://github.com/project-chip/connectedhomeip/issues/31447).

**Comment by hicklin** [comment]
This issue was addressed by PR #31451.
