### ISSUE TITLE
[ICD] Add TestEventTrigger for LIT that support enable/disable and specify specify the LIT time to maybe 30 seconds or so which can be used

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#31379]
In order to test LIT in certification test, we need add a capability in TestEventTrigger(https://github.com/project-chip/connectedhomeip/blob/caea3ec81b8c1f1e690323a00426301dd9c9a05a/src/app/TestEventTriggerDelegate.h#L27) that can control two flags, one flag can disable long idle time for non long idle time tests and another flag which can specify the LIT time to maybe 30 seconds or so which can be used for testing.

TestEventTrigger is an attribute in diagnostic cluster(https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/0f07d0c7ad51aaf32c343d647dae8aa5ad768761/src/service_device_management/DiagnosticsGeneral.adoc#59-testeventtriggersenabled-attribute), tester can use TestEventTrigger to modify the above LIT things.

**Comment by yunhanw-google** [comment]
I think we also need to use TestEventTrigger to adjust operatingMode attribute between sit and lit for dynamic ICD feature validation during certification test. @lpbeliveau-silabs @jmartinez-silabs @mkardous-silabs

**Comment by jmartinez-silabs** [comment]
That should be done by registering/unregistering the monitoring client

**Comment by yunhanw-google** [comment]
@jmartinez-silabs could you elaborate a little bit more between monitoring client registration and dynamic ICD switch? Thanks

**Comment by tcarmelveilleux** [comment]
We need to be able to:

- Disable LIT behavior entirely for test purposes, so that an ICD configured by a commissioner to have LIT registration can be tested for non-LIT tests without crazy time-outs. This could be done at commissioning time before commissioning complete. Otherwise, it's possible you have to wait for long check-in delay before you can unregister.
- Force the LIT behavior to be at a max sleep interval that is much lower than what the product would do in the field, so that test cases can be done with delays of >= ~30s (e.g. just out of SIT bounds), rather than waiting for real hours.

**Comment by mkardous-silabs** [comment]
@tcarmelveilleux @yunhanw-google agreed on both posts. The test event trigger will allow to force specific states for different tests cases.

The only thing i don't think is necessary is the bits for dynamic lit / sit ie. Smoke&Co tests. We won't need the test event trigger; not for the ICD bits at least.

**Comment by yunhanw-google** [comment]
Agree. Thanks

**Comment by yunhanw-google** [comment]
We also need one way to test RefreshKey, maybe create a initial counter + uint32_max via TestEventTrigger.
