### ISSUE TITLE
[Trivial] Concentration Measurements Cluster should have methods to set attributes to NULL

### ISSUE THREAD

**Issue by olavt** [project-chip/connectedhomeip#31446]
### Type

Other

### Explanation

The Measurements clusters like the Temperature Measurement cluster have methods like this to set an attributes value to NULL:

chip::app::Clusters::TemperatureMeasurement::Attributes::MeasuredValue::SetNull(TEMPERATURE_SENSOR_ENDPOINT);

For the Concentration Measurement Clusters a similar method does not seem to exist.

There should be similar ways to set the attributes values to NULL for the Concentration Measurement Clusters.

### Platform

all

### Testing

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
What would the methods do?  The attributes are not being stored in the global attribute store, so there is nothing to set to any value, null or not.  That's why those methods don't exist: they only manipulate the global store, and that's not relevant here.

The right way to do this is to use `SetMeasuredValue` or the like on the relevant `Clusters::ConcentrationMeasurement::Instance`.

**Comment by olavt** [comment]
@bzbarsky-apple 

What is the correct syntax to call SetMeasuredValue and set it to NULL?

This is how it's called with the regular value:

SetMeasuredValue(MakeNullable(2.0f));

Not sure how to pass it NULL.

**Comment by bzbarsky-apple** [comment]
`SetMeasuredValue(NullNullable)`.
