### ISSUE TITLE
echo-ble triggers network provisioning with invalid ssid/password

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#3407]
Repro: on a mac, `chip-tool echo ble 3840 12345678`
```
I (892834) rendezvous-devicedelegate: Device completed SPAKE2+ handshake

I (892834) wifi-echo-demo: Display awake but will switch off automatically in 30 seconds
I (893874) chip[NP]: Received kWiFiAssociationRequest. DeviceDelegate 0x3ffe5fa0

I (893874) chip[NP]: ESP32NetworkProvisioningDelegate: SSID: , key: 
```

@pan-apple
@andy31415

**Comment by pan-apple** [comment]
Tag: @vivien-apple

**Comment by vivien-apple** [comment]
@pan-apple `echo` capabilities over BLE has been removed in your cleanup right ? 

I was planning to convert `echo ble` to 'pair ble' at some point so that's fine.
I haven't looked in details, is there something like `PersistentStorageDelegate` for the device side ? Or is it up to the demo app at the moment ?

**Comment by woody-apple** [comment]
@vivien-apple is this still relevant?

**Comment by vivien-apple** [comment]
Nope. The `echo` command was handcrafted and it does not exists anymore.
