### ISSUE TITLE
Get Matter UniqueID of Matter Device using MatterSupport Framework for Alexa App2App Linking [iOS] [Tooling] [darwin]

### ISSUE THREAD

**Issue by kshrikant** [project-chip/connectedhomeip#34072]
### Reproduction steps / Feature

Hello there, I'm recently started working on Matter devices for iOS. Currently I'm working for App2App linking with Alexa. 

For instance you can refer this [Alexa.Commissionable Interface 1.0](https://developer.amazon.com/de-DE/docs/alexa/device-apis/alexa-commissionable.html#Matter_protocol_requirements)

Were we are doing - [AddOrUpdateReport](AddOrUpdateReport) you can get more about here in below flow diagram. 

Our need is to figure it out `customIdentifier` So can someone please/share help with me how to get it ?

<img width="980" alt="Screenshot 2024-06-25 at 6 59 26 PM" src="https://github.com/project-chip/connectedhomeip/assets/9281639/477fcf3a-9bb8-4b53-b33f-3aac53a75b90">

For reference here is the flow -

<img width="1412" alt="Screenshot 2024-06-21 at 7 00 16 PM" src="https://github.com/project-chip/connectedhomeip/assets/9281639/6f3492a5-3b19-497d-934d-1408499af786">

Similar question - https://forums.developer.apple.com/forums/thread/725724

### Platform

darwin, iOS, other

### Type

Hardware validated

### Anything else?

Similar thread were I got to see same question but didn't answered. 

[How do I obtain the unique ID of matter device using Matter support framework](https://forums.developer.apple.com/forums/thread/725724)

**Comment by bzbarsky-apple** [comment]
This does not sound like an issue with any code in the Matter SDK.

If your issue is with Apple's MatterSupport (not Matter) framework, please file a Feedback Assistant ticket.  Let me know the ticket ID and I will have it followed up on.

If your issue is with some Alexa API I don't know where those issues should be reported.

Looking at the linked thread at https://forums.developer.apple.com/forums/thread/725724 there seems to be some serious confusion there: you use MatterSupport to get the device onto the network and open a commissioning window on it.  Then you use Matter.framework to commission the device.  As part of doing that, you can read data from the device once the PASE session is established and whatnot.
