### ISSUE TITLE
[1.4][TC-EEVSE-2.3] Python script has to be updated by adding step 22 as per the test plan

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#34576]
### Feature Area

Other

### Test Case

TC-EEVSE-2.3

### Description
- In TC-EEVSE-2.3, Step 22 has been added in Python script as per the test plan.

**Python script reference:** https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_EEVSE_2_3.py

**Test plan reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/energy_EVSE.adoc#tc-eevse-2-3-optional-chargingpreferences-feature-functionality-with-dut_server
 

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/commit/13fe13ae3b61a5b9adb3b1ab8248fa3db11dddf2

### Platform

raspi

**Comment by jamesharrow** [comment]
This is a **minor** misalignment between the test plan and the test script.

I would still recommend running the existing test scripts for TE#2 since the only step is missing in the test script is a clean up action (which doesn't really do anything).

I will raise a small PR to correct the script (adding the new call to Test Event trigger) at the end.

The SDK / Example app will support this extra step at the end already.
