### ISSUE TITLE
[Test Failed] EWATERHRT1.1: Failure return on reading Feature-Map and Cluster Revision attribute.

### ISSUE THREAD

**Issue by jadhavrohit924** [project-chip/connectedhomeip#34977]
### Test issue(s)

DUT returned failure when a read command was sent from the controller for feature-map and cluster-revision attributes.

### Anything else?

[chip_tool.txt](https://github.com/user-attachments/files/16611372/chip_tool.txt)
[device.txt](https://github.com/user-attachments/files/16611373/device.txt)

**Comment by jamesharrow** [comment]
This was on ESP32 all-clusters-app - so maybe the cluster isn't correctly configure in ZAP to say where these two attributes come from?

**Comment by bzbarsky-apple** [comment]
@jamesharrow The ZAP part is fine.  It's just that `Clusters::WaterHeaterManagement::WhmApplicationInit` happens only in `all-clusters-app/linux/main-common.cpp`, but this is _esp32_, not _linux_.

As in, the other all-clusters apps have to be fixed to call this bit too.

**Comment by jamesharrow** [comment]
@PeterC1965 is reworking this to move WaterHeater from all-clusters into Energy Management App and then to have a ESP32 and Silabs version which is compatible with Linux.

PR in progress: https://github.com/project-chip/connectedhomeip/pull/34886

**Comment by jamesharrow** [comment]
Note that https://github.com/CHIP-Specifications/chip-test-plans/issues/4509 has proposed removing the TC-EWATERHTR-1.1 test from the test plan because it is covered by the TC-IDM-10.2 Conformance Testing now.

To confirm - the https://github.com/project-chip/connectedhomeip/pull/34886 has been manually tested on ESP32 to check that this now works with energy management app with water heater logic enabled.
