### ISSUE TITLE
[BUG] Commissioning Failure on Google PF with Thread device, "Can't connect to thread network"

### ISSUE THREAD

**Issue by nxtm555** [project-chip/connectedhomeip#35113]
### Reproduction steps

- Process
step1: Setup Google ecosystem  (Nest Hub 2nd, Pixel 6a).
step2: commission the Matter over Thread device from google home app.
step3: After passing Matter authentication, the device will fail when joining the Thread network.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

1.1

### Platform

android

### Platform Version(s)

Android 14

### Anything else?

- Envilonments
Google Nest Hub(2nd gen) : 3.73.411796
Pixel 6a : Android 14
Google Home app : 3.19.1.3, 3.20.1.8
Thread matter device : Matter v1.1

- NOTE
We have 3 Matter over thread devices with same board and same farmware. 
Only 1 out of 3 devices will pass Matter authentication.
We use Vendor ID which is issued by Alliance.

![Screenshot_20240807-110320](https://github.com/user-attachments/assets/cdcd2f01-5d48-463c-9ecc-0c6e28827b97)
[FAIL-ThreadNetwork_GoogleNesthub_Commissioning.log](https://github.com/user-attachments/files/16684972/FAIL-ThreadNetwork_GoogleNesthub_Commissioning.log)

**Comment by andy31415** [comment]
This seems to be google-specific rather than an SDK issue. I would suggest to try the google-specific communities mentioned at https://developers.home.google.com/matter, like https://stackoverflow.com/questions/tagged/google-smart-home or https://www.googlenestcommunity.com/t5/Smart-Home-Developer-Forum/bd-p/Smart-Home-Developer-Forum
