### ISSUE TITLE
[1.1] Failed to commission with Google Nest Hub.

### ISSUE THREAD

**Issue by NNAA0917** [project-chip/connectedhomeip#35120]
### Reproduction steps

I am implementing a Matter device using the STM32WB5MMG. When attempting to commission the device with a Google Nest Hub, it fails to join the Thread Network.

Upon reviewing the logs, it appears that the NOC (Node Operational Certificate) verification is successful, but when trying to connect t
[STM32WB5MMG_GoogleNestHub_Commissioning_Error.txt](https://github.com/user-attachments/files/16687491/STM32WB5MMG_GoogleNestHub_Commissioning_Error.txt)
o the Google Nest Hub using the Thread Network information, there seems to be no response from the Google Nest Hub.

Could you suggest any solutions for this issue?

### Bug prevalence

always

### GitHub hash of the SDK that was being used

5a21d17

### Platform

other

### Type

Platform Issue

**Comment by andy31415** [comment]
This seems to be google-specific rather than an SDK issue. I would suggest to try the google-specific communities mentioned at https://developers.home.google.com/matter, like https://stackoverflow.com/questions/tagged/google-smart-home or https://www.googlenestcommunity.com/t5/Smart-Home-Developer-Forum/bd-p/Smart-Home-Developer-Forum
