### ISSUE TITLE
Investigate .bss usage of gSessions

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#3519]
1.1%  5.95Ki    ../../third_party/connectedhomeip/examples/common/chip-app-server/Server.cpp
    79.6%  4.73Ki    .bss
      37.1%  1.76Ki    (anonymous namespace)::gRendezvousServer
      34.5%  1.63Ki    (anonymous namespace)::gTestPairing
      28.4%  1.34Ki    (anonymous namespace)::gSessions

**Comment by pan-apple** [comment]
This issue is related to memory consumed by `chip::Transport::PeerConnectionState mStates[16];` in `SecureSessionMgrBase` class. The memory consumption is related to number of peer connection states the object is maintaining. The number of peer connections is configurable by `CHIP_CONFIG_PEER_CONNECTION_POOL_SIZE`. So that could be used to reduce the memory consumption. But, if it is not significant amount of memory, maybe we should keep it to the default value.

**Comment by kpschoedel** [comment]
Obsolete — `gSessions` doesn't even exist any more.
