### ISSUE TITLE
ZCL implement emberAfDefaultResponseCallback

### ISSUE THREAD

**Issue by jepenven-silabs** [project-chip/connectedhomeip#3523]
#### Problem
ZCL `emberAfDefaultResponseCallback` is not implemented

 #### Proposed Solution
Implement `emberAfDefaultResponseCallback` if needed

**Comment by vivien-apple** [comment]
I think we can just close this. `emberAfDefaultResponseCallback` is what is used under the hood to fire callbacks for command responses. I *think* this bug was opened because the whole set of callbacks was removed from the `gen/` code in the first version of patch trying to migrate from `AppBuilder` to `ZAP`
