### ISSUE TITLE
[1.3] Processing that occurs after completion with the Apple platform

### ISSUE THREAD

**Issue by NNAA0917** [project-chip/connectedhomeip#36454]
### Reproduction steps

We are developing with Matter v1.3.
After commissioning with HomePod Mini, we want to put the device into Sleep Mode.
If the device is put into Sleep Mode after DeviceEventType::kCommissioningComplete occurs, commissioning will fail.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

5bb5c9e

### Platform

other

### Platform Version(s)

1.3

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
You can't just go into sleep mode without waiting the requisite active intervals as advertised by your device.  Just because CommissioningComplete happened does not mean the client is done talking to you....

**Comment by NNAA0917** [comment]
Thank you for checking.
So, what kind of implementation would be appropriate?

The current development environment is as follows.
Hardware: STM32WB5MMG-DK
Software: X-CUBE-MATTER
Platform: Apple (Homepod mini, iPhone)
Matter SDK v1.3
Device Type: OnOff Plug

**Comment by NNAA0917** [comment]
If you follow the specifications, at what stage is it appropriate to enter Sleep Mode?

**Comment by bzbarsky-apple** [comment]
Again: after any network activity, you have to stay in active mode for ActiveModeThreshold.

The general rules for when you can go into idle mode are somewhat complicated and depend on what else is going on (e.g. whether any active exchanges exist, whether a fail-safe is armed, etc, etc).  I would hope you would go into sleep mode when the core SDK says you can by switching to idle mode, because that's when you're allowed to do it.

**Comment by NNAA0917** [comment]
Thank you.
Is the ICD-Manager-Server required when using Sleep Mode?

**Comment by bzbarsky-apple** [comment]
>  Is the ICD-Manager-Server required when using Sleep Mode?

If you're going to sleep for more than about 15s, then yes.
