### ISSUE TITLE
CHIP BLE name in raspi cannot be set, it shows ubuntudesktop

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4063]
CHIP BLE name in raspi cannot be set, it shows ubuntudesktop, instead of showing CHIP-1383 or CHIP-3840

**Comment by erjiaqing** [comment]
Generally we does not consider this as a issue since it does not block chip device from communicating with other devices, however, this might confuse the user and vendors might want it to be some specific name.
As for this issue, I believe there are some conflicts with ubuntu desktop's bluetooth manager with chip.
I believe this should be documented instead of code change since it works on ubuntu server.
