### ISSUE TITLE
implement BLE central for Linux, chip tool pairing over BLE fails on linux 

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4113]
BLE central implementation for Linux is not complete. 

sudo ./out/host/chip-tool pairing ble XXX YYY 012345678 3840
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 112233

CHIP:DL: wpa_supplicant: connected to wpa_supplicant proxy
CHIP:DL: wpa_supplicant: WiFi interface: /fi/w1/wpa_supplicant1/Interfaces/1
CHIP:DL: Avahi client registered
CHIP:DL: CHIP task running
CHIP:DL: FAIL: BLE name is NULL in ConfigureBluezAdv
CHIP:DL: Disabling CHIPoBLE service due to error: Error 4003 (0x00000FA3)
CHIP:DL: wpa_supplicant: connected to wpa_supplicant interface proxy
CHIP:TOO: No response from device
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller

**Comment by andy31415** [comment]
During todays SWTT meeting we proposed to deprecate chip-tool and only support the python wrapper for chip automation going forward.

The assumption for this issue is that BLE central fixes for linux affect the chip library and are not chip-tool specific.

@Damian-Nordic : is this assumption correct? assuming you make chip-tool work today, is it reasonable to assume that this will make the python wrapper work on linux once we move to only python?

**Comment by Damian-Nordic** [comment]
@andy31415 I believe the python tool has its own implementation of the BLE central, written in Python (see `ChipBluezMgr.py` file) and CHIP simply forwards all necessary function calls to the python side. It's similar to how Android CHIPTool works. What I have implemented is the BLE central implementation in C++, so it's necessary for native Linux controllers, such as chip-tool. Do you think it's still useful that I integrate my changes even if we (maybe temporarily) won't have any native controllers once we remove chip-tool?
