### ISSUE TITLE
TestBdxTransferSession tries to read out of packetbuffer bounds

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#4748]
#### Problem
In `TestBdxTransferSession.cpp`, `VerifyStatusReport` does:
```
    Encoding::LittleEndian::Reader reader(msg->Start() + headerSize, msg->DataLength());
```
This is starting reading `headerSize` bytes into the data, but still claiming the full data length is available to be read, which seems wrong.

 #### Proposed Solution
Consume `headerSize` bytes first, then just pass `Start()` as the first arg.  Or subtract `headerSize` from the data length if we don't want to change the packet buffer state.  Or something.

@holbrookt

**Comment by holbrookt** [comment]
Thanks for catching this. My goal with this line was to parse the data in the message without doing `Consume()` because the same message may be passed to a `HandleMessage()` method after this, so the `Start` pointer needs to be set to the beginning of the header. 

I'll subtract `headerSize` from the data length like you suggested
