### ISSUE TITLE
[ZAP] We need an XML reflection of feature bits

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#6756]
#### Problem
Currently, we can only specify Mandatory or Optional for an attribute or command definition, but a lot of them are controlled by its Feature bits in CHIP spec. Such as 'ERRCNT'. Vendor should be able to enable or disable those cluster element by enabling/disabling those Feature bits from UI.

 #### Proposed Solution
 We need an XML reflection of feature bits (

**Comment by tecimovic** [comment]
Moved to zap: https://github.com/project-chip/zap/issues/150

**Comment by tecimovic** [comment]
I've moved all the "chip_zap_support" labeled bugs into the zap repo itself under https://github.com/project-chip/zap/issues
I propose that we delete the `chip_zap_support` label, and all the bugs in this repo, and in the future simply open the issues in the zap repo itself, since it's much easier to keep track.

But given that I'm not sure how this repo is tracking "dependent issues" it's not my call.
