### ISSUE TITLE
 gn_build.sh compilation failure happens after PR 7080 landed

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7200]
#### Problem
see gn_build.sh compilation failure happens after PR 7080 landed, after reverting, it works.

 -- Build: GN configure
'--------------------------------
ERROR at //examples/platform/linux/AppMain.cpp:28:11: Include not allowed.
#include <lib/shell/Engine.h>
^-----------------
It is not in any dependency of
//examples/platform/linux:app-main
The include file is in the target(s):
//src/lib/shell:shell_core
which should somehow be reachable.

**Comment by mspang** [comment]
This  requires a bit of understanding how the checker works
- Only headers that belong to targets in loaded build files are diagnosed. So if a build file is not loaded, there will be no errors regarding its headers
-  In this case the shell build file is not loaded in CI because the feature is disabled by default
-  The unified configuration happens to load the shell build file through another dependency path, allowing the error to be diagnosed

Adding a preprocessor condition around the #include makes the code correct. Unfortunately, another limitation of the checking is that it doesn't preprocess the code so there will be a false positive. For such cases, there is a suppression available - the conditional include can be tagged with // nogncheck
