### ISSUE TITLE
[shell] Shell app is not able to receive the incoming message after refactor 

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#7519]
#### Problem
We found the Shell app was not able to receive the incoming message after moving common shell commands to core library.

https://github.com/project-chip/connectedhomeip/pull/6765

```
> ping 192.168.86.171
IP address: 192.168.86.171
CHIP:IN: TransportMgr initialized
CHIP:IN: TransportMgr initialized
CHIP:DL: writing settings to file (/tmp/chip_counters.ini.tmp)
CHIP:DL: failed to rename (/tmp/chip_counters.ini.tmp), Operation not permitted (1)
CHIP:IN: local node id is 0x000000000001b669
CHIP:IN: New pairing for device 0x0000000000bc5c01, key 0!!
Establish secure session succeeded

Send echo request message with payload size: 32 bytes to Node: 12344321
CHIP:IN: Secure message was encrypted: Msg ID 1
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 41723455 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
No response received

Send echo request message with payload size: 32 bytes to Node: 12344321
CHIP:IN: Secure message was encrypted: Msg ID 2
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 41724456 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
No response received

Send echo request message with payload size: 32 bytes to Node: 12344321
CHIP:IN: Secure message was encrypted: Msg ID 3
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 41725456 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
No response received
Done

```

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by gjc13** [comment]
This is caused by the `sleep` in the ping client blocking the stack's event loop.

In https://github.com/project-chip/connectedhomeip/pull/6765/files#diff-496ba0c0f1f6757d9f58a66cd245c61b28f327c03872e45a44125780eb177189R255 , the handling of the shell tasks are posted to the stack's main loop rather than handled in the shell task now.

Modifying it back to processing in the shell task will unblock the ping but I believe it's not the correct thing to do for various reasons:

* CHIP objects and APIs are never thread-safe
* Calling CHIP APIs on the shell task requires another deep stack which is a burden on embedded systems.

My proposal is to modify the echo client to make it async, thoughts? @yufengwangca
