### ISSUE TITLE
Make number of command/read/write client/handler configurable

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#8006]
We can add macro in different platform to make it configurable.

Context:
> Why did we choose 4? Is there a better path forward here for constrained devices? @bzbarsky-apple ?

@bzbarsky-apple @woody-apple I think we have clear TODO "Make number of command/read/write client/handler configurable"

The right numbers are something like:

ReadHandler/WriteHandler/CommandHandler: 1, possibly allocated on the stack, not living in bss. Questionable whether these objects should even exist in their current form, especially CommandHandler (which has a bunch of unused members, etc).
Constrained device ReadClient/WriteClient/CommandClient: Depends on the device, between 0 and 1.
Unconstrained device ReadClient/WriteClient/CommandClient: infinite, bounded by available RAM (and maybe not even that, for devices with swap).
This PR is sort of no worse than the state before; Sagar's attempts to use this on iOS will still be broken and he will need to bump these numbers to much larger values to get anything usable, our CI will still work because it does one thing at a time.... But it's not really any better than the state before either. We should stop wasting our time twiddling these constants and actually solve the real problems.

_Originally posted by @yunhanw-google in https://github.com/project-chip/connectedhomeip/issues/7967#issuecomment-870181926_

**Comment by bzbarsky-apple** [comment]
Please see https://github.com/project-chip/connectedhomeip/pull/7967#issuecomment-870761884 for what I think should actually happen here.

**Comment by erjiaqing** [comment]
> Please see [#7967 (comment)](https://github.com/project-chip/connectedhomeip/pull/7967#issuecomment-870761884) for what I think should actually happen here.

> * ReadHandler/WriteHandler/CommandHandler: 1, possibly allocated on the stack, not living in bss.  Questionable whether these objects should even exist in their current form, especially CommandHandler (which has a bunch of unused members, etc).

Given the fact that there might be trunked data in read / write, there might be more than 1 active ReadHandler and WriteHandler. And as for the case of CommandHandler, it could be 1 if all command transaction are short, however, if there are commands have some background processing, there might also be more than one CommandHandler.

> * Constrained device ReadClient/WriteClient/CommandClient: Depends on the device, between 0 and 1.

The same, we should be able to having more than one active read / write / command transactions since they are async operations even on constrained devices. We can let the project to choose the actual number, and yes, no Read/Write/Command client should be OK -- They can also be a switch to disable related code.

> * Unconstrained device ReadClient/WriteClient/CommandClient: infinite, bounded by available RAM (and maybe not even that, for devices with swap).

Agree, malloc and other similar operations is not limited, we don't have to limit the number of Read/Write/Command clients.

**Comment by bzbarsky-apple** [comment]
> Given the fact that there might be trunked data in read / write

Ah, chunking.  Yes, ok, good point.

> however, if there are commands have some background processing, there might also be more than one CommandHandler.

Yes, but the point is this depends on the exact implementation details of the device and its commands, and it's those implementation details that should control the state we need to capture and where it's stored.
