### ISSUE TITLE
Add chunking support for IM write request

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#8029]
Follow spec https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Encoding-Specification.adoc#chunking

**Comment by mrjerryjohns** [comment]
This will be needed if we want ACL cluster to work correctly.

@bzbarsky-apple @tcarmelveilleux @mlepage-google

**Comment by erjiaqing** [comment]
With some quick thought, and given the fact that the MCU should have the capability to handle chunked write, I think we may have a quick and dirty solution.

IIRC chained buffer cannot be used for handling chunked write, since reading the data between gaps can be a issue.
Then my idea is:
- maintain a buffer on the server side, and then just do exactly the same as buffered read.
- Only support only one chunked write transaction
- The client side also need to maintain a buffer, to hold the data since we need to hold the ownership of the data.

However, maintaining a buffer on the server side seems not affordable on a MCU, so another plan is:

- On the client side, maintain a shortlived buffer, to hold the ownership of data.
- On the server side, add the support to list AppendItem operation

This path is a bit simplier, however, each cluster must support handling the append operation, and it might have some issues related to message integrity(?).

Also, in this case, the client will receive more than one status report (infact, it is 1 + # of elements in the list), seems we can defer the response, and notify the application if the write transaction is finished.

Both the client and server should be aware of potential failures. Can we add another callback to write handler to notify the cluster it is safe to "commit" the data received?
