### ISSUE TITLE
☂️ Transition client-side logic over to `SingleInvokeInitiator` & cluster objects

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#8896]
#### Problem
Once #8894 has been fixed and `SingleInvokeInitiator` has been implemented, the client-side code that currently interfaces with CommandHandler should be ported over to using this new class + cluster objects.

However, to make this a gradual transition, it has been broken down into 5 different phases that are designed to maximize parallelism and ensure smaller sized PRs:
* #8958
* #8960
* #8961 
* #8967
* #8968

This is an 'umbrella' issue that to be deemed fixed, requires the above 5 issues to be fixed first.

**Comment by mrjerryjohns** [comment]
Will add links to the above issues tomorrow...

**Comment by mrjerryjohns** [comment]
@bzbarsky-apple FYI.

**Comment by woody-apple** [comment]
What is the impact of this?

**Comment by bzbarsky-apple** [comment]
The main impacts I know about:

* Broken error-handling in commissioning because the APIs it's using don't propagate out errors correctly.
* Lots of nearly-unused code floating around that we could delete if we stopped using the last few bits of it.

Fixing https://github.com/project-chip/connectedhomeip/pull/13371 is likely to fix this, fwiw.

**Comment by yunhanw-google** [comment]
this has been fixed for C1-C5
