### ISSUE TITLE
Accessories assign the same instance name for Commissionable Node Service

### ISSUE THREAD

**Issue by doublemis1** [project-chip/connectedhomeip#8931]
#### Problem
Each accessory assigns the same instance name for the Commissionable Node service.

Device1:
```
instance:"000000014A77CBB3-0000000000000002", name:"_matter._tcp", state:Registered, port:5540, priority:0, weight:0
--
instance:"7F785DB45B043129", name:"_matterc._udp,_S0,_L3840,_C1,_V9050", state:Registered, port:5540, priority:0, weight:0
Done

```

Device2:

```
instance:"000000014A77CBB3-0000000000000003", name:"_matter._tcp", state:Adding, port:5540, priority:0, weight:0
--
instance:"7F785DB45B043129", name:"_matterc._udp,_S0,_L3840,_C1,_V9050", state:Adding, port:5540, priority:0, weight:0
Done

```

Full commissioning of the second device failed to resolve the IP address because of failure during sending SRP client services to OTBR.

 #### Proposed Solution
The instance name should be random

**Comment by mhazley** [comment]
I think I've been hitting a really similar problem, when I factory reset a device and then re-add it, it fails to register with SRP due to being a duplicate record. If I go to the border router and disable and enable the SRP server, it seems to work ok and allow the device to register. 

Where is the instance id assigned? I can't seem to find it in the code....
