### ISSUE TITLE
ZCLWrite should return "INVALID_VALUE" instead of success & truncation in case of invalid payloads.

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/connectedhomeip#9008]
#### Problem
[zclwrite error.txt](https://github.com/project-chip/connectedhomeip/files/6984810/zclwrite.error.txt)
[zclwrite error2.txt](https://github.com/project-chip/connectedhomeip/files/6984837/zclwrite.error2.txt)

When sending zclwrite command with invalid value, command returns EMBER_ZCL_STATUS_SUCCESS. Subsequent zclread of the attribute would return values such as 0, truncated string that matched requirements, and etc.

Expecting zclwrite to return EMBER_ZCL_STATUS_INVALID_VALUE if invalid value is given.

example: (zclwrite error2.txt)
"zclwrite OnOff OffWaitTwrite OnOff OffWaitTime 1111 1 0 -1" returns success, and "zclread OnOff OffWaitTwrite OnOff OffWaitTime 1111 1 0" returns 65535

in addition, writing valid value does not always return expected result from zclread. (zclwrite error.txt)
"zclwrite Basic Location 8067 0 0 US" wrote successfully; however, zclread returns "value='U'"; expecting value to be "US"

**Comment by erjiaqing** [comment]
> #### Problem
> [zclwrite error.txt](https://github.com/project-chip/connectedhomeip/files/6984810/zclwrite.error.txt)
> [zclwrite error2.txt](https://github.com/project-chip/connectedhomeip/files/6984837/zclwrite.error2.txt)
> 
> When sending zclwrite command with invalid value, command returns EMBER_ZCL_STATUS_SUCCESS. Subsequent zclread of the attribute would return values such as 0, truncated string that matched requirements, and etc.
> 
> Expecting zclwrite to return EMBER_ZCL_STATUS_INVALID_VALUE if invalid value is given.
> 
> example: (zclwrite error2.txt)
> "zclwrite OnOff OffWaitTwrite OnOff OffWaitTime 1111 1 0 -1" returns success, and "zclread OnOff OffWaitTwrite OnOff OffWaitTime 1111 1 0" returns 65535

Currently, IM just reencodes the value and passes the value to ember to store. Ember does not check the length of value so it does not raise an error.

Solution is to add extra check on im-compatibility-functions.

> 
> in addition, writing valid value does not always return expected result from zclread. (zclwrite error.txt)
> "zclwrite Basic Location 8067 0 0 US" wrote successfully; however, zclread returns "value='U'"; expecting value to be "US"

This is another issue, after checking the zap files, the Location is a string which size is 2, however, it is expected to be 3 since there is one byte length preceed. @vivien-apple I would expect the ZAP tool can add the extra one or two bytes to the size of string? (i.e. It will display 2 on GUI, but it will emit 3 (or 1+2 for better readibility) in code.
