### ISSUE TITLE
Add client-side API to handle and process IM events.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9586]
#### Problem
Need API to handle and process iM events in controller side.

**Comment by trombadore** [comment]
This is blocking Matter Test Harness.

For certain controller certification tests, a simulated node needs to be able to handle events like StartUp, ShutDown and Leave. @vivien-apple's simulated nodes for these controller tests leverage the matter stack to handle events. Therefore this bug needs to close so that the Matter stack supports events and thus the simulated nodes leveraged by the test harness can handle events as well.

**Comment by mrjerryjohns** [comment]
Fixed in #11615

**Comment by mrjerryjohns** [comment]
If there are further requirements on the controller side, please open a new issue.
