### ISSUE TITLE
Close subscription earlier if handler fails to retry MRP message

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9596]
Imagine this scenario:
I establish session
I establish subscription
session is closed or handler fails to retry MRP message
I establish new session
I try to reestablish subscription
subscription table is full
then it fails..

So currently we rely on onMessageTimeout to notify IM something bad happens in lower layer, seems we can close the session earlier where message layer detect the error earlier and notify the IM earlier?

**Comment by msandstedt** [comment]
Also posted in #9510.

My view is this.  We have a problem where we've organized a series of singletons, session manager -> exchange manager -> IM engine, where lower layers do not have visibility into what of their resources upper layers are reliant upon.

So for instance, if a session closes and this is not app-initiated, there is no way for the session manager to trigger a failure callback chain to release resources in the exchange layer, IM layer and app. This can happen in at least 3 cases: (1) session eviction, (2) peer-initiated session closing, (3) session-layer-initiated closing e.g. for MRP timeout.

The subscription implementation attempts to mitigate this with the liveliness mechanism. That is necessary and good, but it's not enough. The problem is that this is reliant upon the report or sync cadence to release resources. That may be too late. For instance, imagine this sequence:

    peer initiates session
    peer initiates subscription
    [session table becomes full]
    peer closes session
    peer initiates session
    peer initiates subscription
    [oops, session table is still full]

It is not good or necessary for us to break in this case. But to solve this, we would need the session manager to understand the resources bound to sessions and be able to clean them up by trigger a failure callback chain all the way into the app.

From a clean slate, the way to do this would be to not have exchange manager or IM singletons, but instead to have each session hold a table of exchanges and each exchange to point to IM->app context. This would cleanly reflect the 1:many relationship between sessions and exchanges and allow for a very straight forward session-layer-initiated cleanup mechanism. Note also that such a chain can happen cleanly even from the transport layer. For instance, TCP connections close. It ought to be easy to have a chain that looks like TCP close -> session close -> exchange(s) close -> IM error(s) -> app error(s).

Instead, we have an exchange manager singleton that receives the full multiplexed traffic stream from the session layer. This creates the problem I just laid out and has the further consequence that the exchange manager must be session and peer aware. If it was only ever possible for an exchange to be called from an associated session context, we would have a cleaner separation of the layers in our communication stack.

However, given that we do now have this exchange manager singleton and it is likely this will not change, it seems that we need some other approach. I would recommend that we give the session manager a handle to the exchange manager and allow the session manager to notify the exchange manager when a session is evicted or disappears. This, I hope, would give us the immediate failure callback chain we need.
