### ISSUE TITLE
Software Diagnostics cluster name change, missing attributes, and unsupported attributes response from TE5 SDK repo

### ISSUE THREAD

**Issue by jaehs6sam** [project-chip/connectedhomeip#9600]
#### Problem

During TE5 test case verification using chip-device-ctrl command of SDK TE5 branch, the following issues were found while using all-cluster-app as DUT
ex)  command line: chip-device-ctrl > zclread DiagnosticsSoftware ThreadMetrics 12344321 1 0

1. Cluster name needs to be changed from SoftwareDiagnostics → DiagnosticsSoftware
2. The following attributes are missing from SDK - ThreadMetrics (struct), CurrentHeapFree, CurrentHeapUsed
3. The following attributes returns no data from the read response - ClusterRevision, CurrentHeapHighWatermark

Specification References:
11.12.2
 
 * steps to reproduce
ex)  command line
chip-device-ctrl > zclread DiagnosticsSoftware ThreadMetrics 12344321 1 0

 * system configuration
 SDK TE5 branch with Raspi (Controller and controlee)

![image](https://user-images.githubusercontent.com/12516308/132905227-badbc1b9-86e0-4408-b574-eecd4afa6554.png)

 #### Proposed Solution

**Comment by yufengwangca** [comment]
The optional attributes are not available in chip-tool, and I am not able to enable them via ZAP UI. This apply to all clusters. So we decided to focus on those mandatory attributes at TE6 and follow-up with those optional attributes at TE7.

Regarding the naming change, it is caused by the cluster name and its cluster identifier name are not aligned in the spec, filed https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4155 for follow-up.
